import { getAccountDetails } from "@/lib/supabase/auth";
import Link from "next/link";
import { PlatformShell } from "@/components/platform-shell";
import { SavedComparison } from "@/components/marketplace/compare-control";
import { signOut } from "@/app/(auth)/actions";
import { getRequestLocale } from "@/lib/i18n/request";
import type { Dictionary } from "@/lib/i18n/types";
import type { Profile } from "@/lib/supabase/types";

export async function DashboardPlaceholder({ dictionary: t, profile, role }: { dictionary: Dictionary; profile: Profile; role: "client" | "expert" }) {
 profile = await getAccountDetails(profile);
 const ro = await getRequestLocale() === "ro";
 return <PlatformShell><main className="commerce-page"><section className="content-panel"><p className="eyebrow">{t["dashboard.profile"]}</p><h1 className="text-3xl font-semibold">{ro ? (role === "client" ? "Contul meu" : "Cont de expert") : (role === "client" ? "My account" : "Expert account")}</h1><dl className="spec-grid"><div><dt>{t["auth.email"]}</dt><dd>{profile.email}</dd></div><div><dt>{t["onboarding.fullName"]}</dt><dd>{profile.full_name || (ro ? "Necompletat" : "Not provided")}</dd></div><div><dt>{t["auth.role"]}</dt><dd>{t[`role.${role}`]}</dd></div><div><dt>{t["onboarding.country"]}</dt><dd>{profile.country_code || (ro ? "Necompletat" : "Not provided")}</dd></div></dl><div className="action-row"><Link href="/onboarding">{ro ? "Editează profilul" : "Edit profile"}</Link><Link href="/forgot-password">{ro ? "Schimbă parola prin e-mail" : "Change password by email"}</Link><form action={signOut}><button className="button-outline">{t["auth.logout"]}</button></form></div></section>
 {role === "expert" && <section className="content-panel"><h2>{ro ? "Profil profesional" : "Professional profile"}</h2><p>{ro ? "Datele profilului sunt private. Completarea lor nu reprezintă verificarea calificărilor și nu publică un profil în directorul de experți." : "Profile details are private. Completing them does not verify qualifications or publish a profile in the expert directory."}</p><Link href="/experts">{ro ? "Despre experți" : "About experts"} →</Link></section>}
 {profile.assistance_type && <section className="content-panel"><h2>{ro ? "Cerințe salvate în cont" : "Requirements saved to your account"}</h2><p className="whitespace-pre-wrap">{profile.assistance_type}</p><Link href="/onboarding">{ro ? "Editează cerințele" : "Edit requirements"}</Link></section>}
 <div className="two-columns"><section className="content-panel"><h2>{ro ? "Cerințe și calcule" : "Requirements and calculations"}</h2><p>{ro ? "Rezultatele calculatoarelor nu sunt salvate în cont. Continuă dimensionarea și păstrează linkul rezultatului acolo unde este disponibil." : "Calculator results are not saved to your account. Continue sizing and keep the result link where available."}</p><div className="link-stack"><Link href="/marketplace/find-my-solution">{ro ? "Găsește soluția potrivită" : "Find my solution"} →</Link><Link href="/calculators/battery">{ro ? "Calculator baterie" : "Battery calculator"}</Link><Link href="/calculators/solar">{ro ? "Calculator solar" : "Solar calculator"}</Link><Link href="/backup-calculator">{ro ? "Calculator autonomie" : "Backup calculator"}</Link></div></section><section className="content-panel"><h2>{ro ? "Echipamente comparate" : "Compared equipment"}</h2><SavedComparison ro={ro}/><div className="link-stack"><Link href="/marketplace">Marketplace →</Link><Link href="/solutions">{ro ? "Soluții" : "Solutions"} →</Link><Link href="/learn">{ro ? "Ghiduri tehnice" : "Technical guides"} →</Link></div></section></div>
 <p className="supplier-disclosure">{ro ? "Achizițiile sunt efectuate la furnizorul extern, care gestionează prețul, stocul, plata, livrarea, garanția și retururile. Contul nu afișează comenzile furnizorilor." : "Purchases take place with the external supplier, who manages price, stock, payment, delivery, warranty and returns. Your account does not display supplier orders."}</p></main></PlatformShell>;
}
