"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { UkraineEnergySnapshot } from "@/types/ukraine-energy";

const ranges = ["Today", "7 days", "30 days", "3 months", "1 year", "Since 2022"];
const sourceUrl = "https://greendealukraina.org/gd-tracker/state-of-the-ukrainian-energy-system";

function unavailable(value: number | undefined, unit = "") { return value === undefined ? "Not available" : `${value.toLocaleString()}${unit ? ` ${unit}` : ""}`; }
function download(snapshot: UkraineEnergySnapshot) { const rows = ["metric,value,status,source", ...snapshot.sources.map((item) => `source,,${item.status},${item.sourceName}`)]; const blob = new Blob([rows.join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "mr-electro-ukraine-energy-demo.csv"; link.click(); URL.revokeObjectURL(url); }

export function UkraineEnergyDashboard({ initialSnapshot }: { initialSnapshot: UkraineEnergySnapshot }) {
  const [snapshot, setSnapshot] = useState(initialSnapshot);
  const [range, setRange] = useState("Today");
  const [addressResult, setAddressResult] = useState<string | null>(null);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const unavailableCount = useMemo(() => snapshot.sources.filter((item) => item.status === "unavailable" || item.status === "demo").length, [snapshot.sources]);
  const refresh = async () => { setIsRefreshing(true); try { const response = await fetch("/api/energy/ukraine", { cache: "no-store" }); if (response.ok) setSnapshot(await response.json()); } finally { setIsRefreshing(false); } };
  const share = async () => { await navigator.clipboard?.writeText(window.location.href); };
  const kpis = [
    ["Power system status", "Not available", "No official operational feed", "System operator feed not connected"],
    ["Net import / export", unavailable(snapshot.flows.find((item) => item.valueMw !== undefined)?.valueMw, "MW"), "Commercial flow only", "Demo fixture"],
    ["Available generation", unavailable(snapshot.capacity[0]?.operatingMw, "MW"), "No verified assessment", "Demo fixture"],
    ["Scheduled-outage regions", unavailable(snapshot.outages.filter((item) => item.plannedHours !== undefined).length), "No current DSO feed", "Demo fixture"],
    ["Gas storage", unavailable(snapshot.gas[0]?.volumeMcm, "mcm"), "Technical gas excluded when supplied", "AGSI adapter pending"],
    ["Day-ahead price", unavailable(snapshot.prices[0]?.uahPerMwh, "UAH/MWh"), "No market feed", "OREE adapter pending"],
    ["Data sources online", `${snapshot.sources.length - unavailableCount}/${snapshot.sources.length}`, "Demo-mode sources", "Source registry"],
    ["Last synchronization", new Date(snapshot.generatedAt).toLocaleString("en-GB", { timeZone: "Europe/Kyiv" }), "Europe/Kyiv", "Local fixture"],
  ];

  return <div className="mx-auto w-full max-w-7xl space-y-6 text-slate-800">
    <section className="brand-glass-card rounded-[2rem] p-6 sm:p-8">
      <div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-start"><div><p className="eyebrow">Ukraine Energy</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-5xl">Ukraine Energy System</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-700">Live and historical information about electricity supply, generation, cross-border flows, market prices, gas reserves and regional outages.</p><p className="mt-4 text-sm text-slate-600">Data status: <b className="text-amber-800">Demo data</b> · Last local fixture update: {new Date(snapshot.generatedAt).toLocaleString("en-GB", { timeZone: "Europe/Kyiv" })} · Europe/Kyiv</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={refresh} className="button-primary">{isRefreshing ? "Refreshing…" : "Refresh"}</button><button type="button" onClick={share} className="button-outline">Share</button><button type="button" onClick={() => download(snapshot)} className="button-outline">Download data</button><Link className="button-outline" href="/methodology">Methodology</Link></div></div>
      <div className="mt-6 flex flex-wrap gap-2" aria-label="Global date range">{ranges.map((item) => <button type="button" key={item} onClick={() => setRange(item)} aria-pressed={range === item} className={`rounded-full px-3 py-1.5 text-sm ${range === item ? "bg-teal-700 text-white" : "bg-white/70 text-slate-700"}`}>{item}</button>)}</div>
    </section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([label, value, detail, source]) => <article key={label} className="info-card rounded-2xl p-4"><p className="text-xs font-semibold uppercase tracking-wide text-teal-800">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p><p className="mt-2 text-xs text-slate-600">{detail}</p><p className="mt-1 text-xs text-slate-500">Source: {source}</p></article>)}</section>
    <section className="grid gap-6 lg:grid-cols-2"><Panel title="Cross-border electricity trade" source="ENTSO-E adapter pending · commercial flows only"><p className="text-sm text-slate-600">Selected period: {range}. No authorised automated source is connected, so imports/exports are not estimated. Physical and commercial flows remain separate.</p><FlowTable snapshot={snapshot} /></Panel><Panel title="Generation capacity status" source="Local demo fixture · unconfirmed"><div className="space-y-3 text-sm"><Bar label="Operating" value={snapshot.capacity[0]?.operatingMw} tone="bg-emerald-500"/><Bar label="Damaged" value={snapshot.capacity[0]?.damagedMw} tone="bg-amber-500"/><Bar label="Temporarily offline" value={snapshot.capacity[0]?.offlineMw} tone="bg-slate-400"/><p className="text-slate-600">No capacity assessment is shown until a dated, attributable source is connected. Technology and facility filters will use the same normalized record model.</p></div></Panel></section>
    <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Panel title="Regional outage outlook" source="DSO adapters pending · demo fixture"><div className="grid gap-2 sm:grid-cols-2">{snapshot.outages.map((outage) => <button type="button" key={outage.oblast} className="rounded-xl border border-teal-100 bg-white/75 p-3 text-left hover:border-teal-400"><b>{outage.oblast} oblast</b><span className="mt-1 block text-sm text-slate-600">Not available — {outage.coverage}</span></button>)}</div><p className="mt-4 text-xs text-slate-600">Historical outage surveys must be labelled by their study period and never presented as current schedules.</p></Panel><Panel title="Address outage check" source="No DSO address feed connected"><form onSubmit={(event) => { event.preventDefault(); setAddressResult("Not available. A verified distribution-system-operator feed is required before address-level schedules can be shown."); }} className="grid gap-3"><select aria-label="Oblast" className="rounded-xl border border-slate-200 bg-white p-3"><option>Choose oblast</option>{snapshot.outages.map((item) => <option key={item.oblast}>{item.oblast}</option>)}</select><input className="rounded-xl border border-slate-200 bg-white p-3" placeholder="City or settlement"/><input className="rounded-xl border border-slate-200 bg-white p-3" placeholder="Street and building"/><button className="button-primary" type="submit">Check schedule</button></form>{addressResult ? <p role="status" className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-950">{addressResult}</p> : null}</Panel></section>
    <section className="grid gap-6 lg:grid-cols-2"><Panel title="Gas storage reserves" source="AGSI adapter pending"><p className="text-sm text-slate-600">Current volume, fill level, injection and withdrawal are not available in the local fixture. Actual and forecast series will be visibly separate once an authorised source is configured.</p></Panel><Panel title="Day-ahead electricity market" source="OREE + NBU adapters pending"><p className="text-sm text-slate-600">No current price is displayed. The future feed will retain timestamp in Kyiv time, UAH/MWh, EUR/MWh, exchange rate and applicable price-cap metadata.</p></Panel></section>
    <p className="rounded-2xl border border-cyan-100 bg-cyan-50/80 p-4 text-sm text-slate-700">This original MR Electro AI dashboard is informed by public methodology, not copied code, graphics, branding or embedded charts. See the <a className="font-semibold text-teal-800 underline" href={sourceUrl} target="_blank" rel="noreferrer">public reference methodology</a>. No current operational or address-level outage data is claimed until authorised sources are connected.</p>
  </div>;
}
function Panel({ title, source, children }: { title: string; source: string; children: React.ReactNode }) { return <section className="info-card rounded-3xl p-5"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="text-xl font-bold text-slate-950">{title}</h2><span className="text-xs text-slate-500">Source: {source}</span></div><div className="mt-5">{children}</div></section>; }
function Bar({ label, value, tone }: { label: string; value?: number; tone: string }) { return <div><div className="flex justify-between text-sm"><span>{label}</span><b>{unavailable(value, "MW")}</b></div><div className="mt-1 h-3 rounded-full bg-slate-100"><div className={`h-full rounded-full ${value === undefined ? "w-0" : tone}`} style={{ width: value === undefined ? "0%" : "100%" }} /></div></div>; }
function FlowTable({ snapshot }: { snapshot: UkraineEnergySnapshot }) { return <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="py-2">Direction</th><th>Commercial flow</th><th>Status</th></tr></thead><tbody>{snapshot.flows.map((flow) => <tr key={flow.counterparty} className="border-b border-slate-100"><td className="py-2">{flow.counterparty}</td><td>{unavailable(flow.valueMw, "MW")}</td><td className="capitalize">{flow.source.status}</td></tr>)}</tbody></table></div>; }
