import { bilingual as b, type LocalText } from "./content";

/** Original worked cases: illustrative assumptions, never a certified design. */
export const guideExamples: Record<string, LocalText> = {
  "how-to-size-backup-battery": b(
    "Consider 1000 Wh of essential AC consumption over an evening. At 80% usable discharge and 92% conversion efficiency, the nominal requirement is approximately 1359 Wh. A documented 12.8 V, 100 Ah battery stores 1280 Wh nominally, so one such battery falls short even before ageing or standby losses. Two batteries are not automatically the answer: the manufacturer must permit the grouping, the batteries must be suitable for joint operation and protection must be designed for the resulting fault current. Alternatively, reduce the load budget, choose a larger approved battery or shorten the autonomy target. Record which change made the system fit. Before comparing price, check whether the proposed inverter can draw its required current without exceeding the battery's continuous discharge limit. Passing the energy calculation only resolves one part of the selection.",
    "Presupune un consum AC esențial de 1000 Wh într-o seară. La 80% descărcare utilizabilă și 92% randament, necesarul nominal este aproximativ 1359 Wh. O baterie documentată de 12,8 V și 100 Ah stochează nominal 1280 Wh, deci una singură nu ajunge, chiar înainte de îmbătrânire sau consumul în gol. Două baterii nu sunt automat soluția: producătorul trebuie să permită gruparea, bateriile să fie potrivite pentru funcționare comună, iar protecția să fie proiectată pentru curentul de defect rezultat. Poți reduce consumul, alege o baterie mai mare sau scurta autonomia. Notează schimbarea care face sistemul suficient. Înainte de preț, verifică dacă invertorul poate primi curentul necesar fără depășirea limitei continue a bateriei. Calculul energetic rezolvă doar o parte din selecție.",
  ),
  "how-to-choose-inverter": b(
    "Suppose electronics consume 350 W and a pump consumes 500 W while running. Simultaneous continuous demand is 850 W. If the measured pump start requires 1800 W, the inverter may see about 2150 W during that event, with the electronics still operating. A 1000 W label alone cannot establish suitability. Ask for the overload curve, its duration and the rating at the installation temperature. Next check the battery: at 850 W and 92% efficiency, a 12.8 V source supplies roughly 72 A at nominal voltage, and more at low voltage. The startup current is a separate battery constraint. If the proposed system fails either check, consider an appropriately rated inverter and battery architecture, or permitted load sequencing. Do not treat a bigger inverter as a cure for an undersized DC supply. Include standby consumption in the energy budget.",
    "Electronica consumă 350 W, iar o pompă 500 W în funcționare. Sarcina continuă simultană este 850 W. Dacă pornirea măsurată a pompei cere 1800 W, invertorul poate vedea aproximativ 2150 W în acel moment, cu electronica pornită. Eticheta de 1000 W nu dovedește compatibilitatea. Cere curba de suprasarcină, durata și puterea la temperatura instalației. La 850 W și 92% randament, sursa de 12,8 V livrează circa 72 A la tensiune nominală și mai mult la tensiune scăzută. Pornirea este o constrângere separată pentru baterie. Dacă una dintre verificări eșuează, analizează altă arhitectură sau secvențierea permisă a sarcinilor. Un invertor mai mare nu repară o sursă DC subdimensionată. Include consumul în gol în bugetul energetic.",
  ),
  "lifepo4-vs-lead-acid": b(
    "Compare two hypothetical batteries with 1200 Wh nominal energy. If the planning limits allow 50% discharge for one and 80% for the other, their usable DC budgets are 600 Wh and 960 Wh respectively. These percentages are chosen assumptions, not universal chemistry specifications. At 90% conversion efficiency, the illustrative AC budgets become 540 Wh and 864 Wh before standby losses. Use the exact manufacturer's discharge curves, temperature limits and cycle-life conditions to replace these assumptions. Then compare the cost of a complete usable system: charger changes, monitoring, mounting and protection can matter as much as the battery price. A battery with a lower initial price may require a larger bank for the same operating duty. Conversely, an existing compatible installation may make retaining its current chemistry reasonable. Document the required service and constraints before deciding by chemistry name.",
    "Compară două baterii ipotetice cu energie nominală de 1200 Wh. Dacă ipotezele permit descărcare de 50% pentru una și 80% pentru cealaltă, bugetele DC utilizabile sunt 600 Wh și 960 Wh. Procentele sunt ipoteze, nu specificații universale ale chimiei. La 90% randament, bugetele AC orientative devin 540 Wh și 864 Wh înainte de pierderile în gol. Înlocuiește ipotezele cu graficele producătorului, limitele termice și condițiile duratei de viață. Compară apoi costul sistemului utilizabil: încărcătorul, monitorizarea, montajul și protecția pot conta la fel de mult ca bateria. Prețul inițial mai mic poate necesita un banc mai mare. În schimb, compatibilitatea instalației existente poate justifica păstrarea chimiei actuale. Definește serviciul necesar înainte de alegerea chimiei.",
  ),
  "12v-vs-24v-vs-48v": b(
    "For an illustrative 2000 W AC load at 92% efficiency, nominal DC current is approximately 181 A at 12 V, 91 A at 24 V or 45 A at 48 V. These values exclude the additional increase as battery voltage falls. They explain why a higher-voltage architecture can reduce current, but they do not specify cable size or make one voltage universally preferable. A caravan with many existing 12 V appliances may need DC conversion if its main bank changes. That converter introduces its own current, efficiency and failure constraints. A 48 V inverter cannot be connected to a 12 V battery simply because the energy capacity is adequate. Create a voltage map listing the battery, PV controller, inverter, chargers and auxiliary loads. Any mismatch requires an explicitly compatible conversion stage or a different component. Verify allowable series connections before buying batteries.",
    "Pentru 2000 W AC și randament 92%, curentul DC nominal este aproximativ 181 A la 12 V, 91 A la 24 V sau 45 A la 48 V. Valorile nu includ creșterea la scăderea tensiunii bateriei. Ele explică reducerea curentului, dar nu dimensionează cablul și nu fac o tensiune universal preferabilă. O rulotă cu multe aparate de 12 V poate necesita conversie DC dacă se schimbă bancul principal. Convertorul adaugă limite de curent, pierderi și un posibil punct de defect. Un invertor de 48 V nu se conectează la bateria de 12 V doar fiindcă energia este suficientă. Desenează harta tensiunilor pentru baterie, regulator, invertor, încărcătoare și aparate. Orice nepotrivire cere conversie compatibilă sau altă componentă. Verifică legarea în serie înainte de achiziție.",
  ),
  "how-many-kwh-do-i-need": b(
    "A 10 W router running for 24 hours uses 240 Wh. A 100 W workstation used for six hours uses 600 Wh. Four 8 W lamps used for five hours add 160 Wh. Together they require 1000 Wh, or 1 kWh, at the loads. A 2000 W kettle used for ten minutes adds about 333 Wh, even though it runs briefly; it also creates a much larger instantaneous power requirement. Decide whether that kettle belongs in the backup budget or can be excluded during an outage. This single choice changes both equipment power and energy needs. A monthly electricity bill cannot reveal that simultaneous peak or identify essential loads. Build a daily table, then a separate outage table using realistic operating times. Measure cycling appliances over a representative interval and repeat the budget for winter if heating controls, lighting or occupancy changes.",
    "Un router de 10 W pornit 24 de ore consumă 240 Wh. Un calculator de 100 W folosit șase ore consumă 600 Wh. Patru lămpi de 8 W aprinse cinci ore adaugă 160 Wh. Totalul este 1000 Wh, adică 1 kWh la consumatori. Un fierbător de 2000 W folosit zece minute adaugă circa 333 Wh și cere mult mai multă putere instantanee. Decide dacă intră în bugetul de rezervă sau poate fi exclus la întrerupere. Alegerea schimbă atât puterea, cât și energia necesară. Factura lunară nu arată acel vârf simultan și nici consumatorii esențiali. Construiește un tabel zilnic și unul pentru întreruperi, cu durate realiste. Măsoară aparatele ciclice pe un interval reprezentativ și repetă bugetul pentru iarnă dacă se schimbă iluminatul, încălzirea sau ocuparea.",
  ),
  "solar-panel-sizing": b(
    "Suppose daily demand is 3000 Wh. With an illustrative 3.5 equivalent full-sun hours and a 0.75 overall yield factor, required array power is approximately 1143 W. At only two equivalent hours with the same factor, that estimate rises to 2000 W. This sensitivity is why a summer result should not be used as a winter guarantee. Check a location-specific monthly yield source such as PVGIS, then consider local shade and mounting separately. A battery may bridge one poor day but does not generate the energy needed to recover afterwards. If the array only replaces average daily consumption, recharging after a deficit may take several days. Compare additional array capacity, reduced consumption or an alternative charging source. Finally, translate array watts into an electrically valid string arrangement using module Voc, temperature correction and controller limits; wattage division alone does not establish compatibility.",
    "Presupune un consum zilnic de 3000 Wh. Cu 3,5 ore echivalente de soare și factor global 0,75, puterea orientativă a panourilor este 1143 W. La doar două ore echivalente, cu același factor, rezultatul crește la 2000 W. De aceea, rezultatul de vară nu garantează funcționarea iarna. Verifică producția lunară locală în PVGIS, apoi separat umbrirea și montajul. Bateria poate acoperi o zi slabă, dar nu produce energia recuperării. Dacă panourile înlocuiesc numai consumul mediu zilnic, refacerea rezervei poate dura mai multe zile. Compară panouri suplimentare, reducerea consumului sau altă sursă de încărcare. Transformă apoi puterea în șiruri electrice valide, folosind Voc, corecția termică și limitele regulatorului. Împărțirea puterilor nu dovedește compatibilitatea.",
  ),
  "mppt-vs-pwm": b(
    "Imagine a 200 W panel with an operating point near 31 V and 6.45 A charging a battery near 14 V. A simplified PWM illustration retains roughly the panel current at battery voltage, about 90 W; real operation depends on the panel curve and conditions. An MPPT controller can convert a larger portion of available panel power into battery-side current, subject to its efficiency and output limits. This example explains the operating principle and is not a guaranteed performance comparison. It does not mean any MPPT unit accepts that panel: maximum PV voltage, short-circuit current, permitted array power and battery charging profile still apply. For a small panel already closely matched to a battery, the cost and complexity tradeoff can differ. Compare usable energy over the intended season and inspect the exact controller manual before choosing a regulation label.",
    "Imaginează un panou de 200 W cu punct de lucru în jur de 31 V și 6,45 A, care încarcă o baterie la circa 14 V. Într-un exemplu simplificat PWM, curentul apropiat de cel al panoului la tensiunea bateriei înseamnă aproximativ 90 W; funcționarea reală depinde de curbă și condiții. MPPT poate transforma o parte mai mare din puterea disponibilă în curent spre baterie, în limitele randamentului și ieșirii. Exemplul explică principiul, nu garantează performanța. Nu orice regulator MPPT acceptă panoul: rămân limitele de tensiune PV, scurtcircuit, putere și profilul bateriei. Pentru un panou mic deja apropiat de tensiunea bateriei, costul și complexitatea pot conduce la alt compromis. Compară energia sezonieră și manualul exact, nu doar eticheta regulatorului.",
  ),
  "inverter-surge-power": b(
    "A 600 W running motor may have a measured start near 1800 W for one second. Add 300 W of electronics that remain on and the system sees about 2100 W during startup. A hypothetical inverter advertised at 3000 W peak for 20 milliseconds has not demonstrated that it can support this event. The battery can also cause a failure even when the inverter curve appears sufficient: BMS overcurrent protection or voltage sag may interrupt the DC supply. Record the event duration, battery state of charge and temperature when evaluating a supervised startup test. If the appliance starts successfully once with a full battery, repeat only within approved operating limits under representative conditions; a single success is weak evidence. Where possible, compare manufacturer-supported soft-start or sequencing options, and recheck machine safety and automatic restart behaviour before changing control settings.",
    "Un motor de 600 W poate avea pornire măsurată de 1800 W timp de o secundă. Cu 300 W de electronică rămasă pornită, sistemul vede circa 2100 W. Un invertor ipotetic cu vârf de 3000 W pentru 20 de milisecunde nu a demonstrat că susține evenimentul. Chiar cu o curbă suficientă a invertorului, BMS sau scăderea tensiunii pot întrerupe sursa DC. Notează durata, starea de încărcare și temperatura la testul supravegheat. O singură pornire reușită cu bateria plină nu dovedește funcționarea în toate condițiile. Testele reprezentative trebuie să respecte limitele aprobate. Analizează pornirea lentă sau secvențierea acceptată de producător și verifică siguranța mașinii și repornirea automată înainte de modificarea comenzilor.",
  ),
  "battery-runtime-calculation": b(
    "Take a documented 1280 Wh nominal battery, an assumed 80% usable fraction and 92% inverter efficiency. Ignoring standby draw initially, the available AC budget is about 942 Wh. A steady 100 W load therefore has an illustrative runtime of 9.4 hours; at 500 W it is about 1.9 hours. Now include a 15 W inverter standby demand on the DC side. For the 100 W load, DC demand becomes approximately 100 / 0.92 + 15 = 124 W, reducing the estimate to about 8.3 hours. The same standby draw matters less proportionally at larger loads. These are planning calculations, not a discharge test or warranty claim. Replace the usable fraction and losses with model-specific data, check current limits independently and leave a suitable reserve rather than planning to operate until an emergency BMS cutoff.",
    "Ia o baterie nominală documentată de 1280 Wh, fracție utilizabilă presupusă de 80% și randament de 92%. Fără consum în gol, bugetul AC este circa 942 Wh. La 100 W constant, autonomia orientativă este 9,4 ore; la 500 W, circa 1,9 ore. Adaugă apoi 15 W consum în gol pe partea DC. Pentru sarcina de 100 W, consumul DC devine aproximativ 100 / 0,92 + 15 = 124 W, iar autonomia scade la circa 8,3 ore. Aceeași pierdere contează proporțional mai puțin la sarcini mari. Sunt calcule de planificare, nu test de descărcare sau garanție. Folosește datele modelului, verifică separat curenții și păstrează rezervă, în loc să planifici până la oprirea de urgență BMS.",
  ),
  "apartment-backup-system": b(
    "For a four-hour interruption, a 15 W router, 40 W lighting load and 60 W laptop need 460 Wh if all run throughout. A refrigerator adds energy according to its measured duty cycle and adds a separate compressor-start requirement. By contrast, operating a 1500 W electric heater for the same four hours adds 6000 Wh. Excluding that heater can change the proposal from a large storage installation to a modest essential-load system. Agree on those exclusions before selecting equipment. A portable unit supplying selected appliances directly has different installation requirements from equipment connected to fixed apartment wiring. Confirm building rules, accessible ventilation, noise and the location of charging equipment. Never assume a balcony makes a combustion generator safe; exhaust can enter nearby dwellings. Review transfer behaviour for routers and computers if even a short interruption is unacceptable.",
    "Pentru patru ore, un router de 15 W, iluminat de 40 W și laptop de 60 W cer 460 Wh dacă funcționează permanent. Frigiderul adaugă energie după ciclul măsurat și o cerință separată de pornire. În schimb, radiatorul de 1500 W pornit patru ore adaugă 6000 Wh. Excluderea sa poate transforma propunerea din stocare mare într-un sistem modest pentru consumatori esențiali. Stabilește excluderile înainte de echipamente. O unitate portabilă care alimentează direct aparate are alte cerințe decât conectarea la instalația fixă. Confirmă regulile clădirii, ventilația, zgomotul și amplasarea încărcării. Balconul nu face automat sigur un generator cu ardere; gazele pot ajunge în alte locuințe. Verifică transferul pentru routere și calculatoare dacă întreruperea scurtă este inacceptabilă.",
  ),
  "home-backup-system": b(
    "Split a hypothetical home into essential circuits and deferrable loads. Router and controls at 50 W for eight hours need 400 Wh; lighting at 100 W for four hours adds 400 Wh. Add measured refrigeration consumption and any pump duty separately. An oven, immersion heater or EV charger can dominate the result, so decide whether each is excluded or deliberately included. The essential-circuit list should be understandable to every household member. An installer then needs the supply arrangement, earthing system, existing distribution-board details and proposed source-transfer method. Those installation facts cannot be inferred from an online energy total. Ask what happens during an outage, restoration of the grid, low battery and a protective-device trip. Document the recovery sequence, and arrange a supervised commissioning check. The final plan should identify which sockets or circuits remain available and which must stay disconnected.",
    "Împarte casa în circuite esențiale și consumatori amânabili. Routerul și comenzile la 50 W timp de opt ore cer 400 Wh; iluminatul de 100 W timp de patru ore adaugă 400 Wh. Adaugă separat frigiderul măsurat și ciclul pompei. Cuptorul, boilerul electric sau încărcarea auto pot domina rezultatul; decide explicit includerea lor. Lista circuitelor esențiale trebuie înțeleasă de toată familia. Instalatorul are nevoie de alimentare, împământare, tabloul existent și metoda de transfer. Aceste date nu se deduc din energia calculată online. Clarifică comportamentul la căderea și revenirea rețelei, baterie descărcată și declanșarea protecției. Documentează revenirea și testul supravegheat. Planul final trebuie să identifice prizele disponibile și circuitele care rămân deconectate.",
  ),
  "rv-solar-basics": b(
    "Assume the caravan uses 1200 Wh per day. An illustrative 400 W array with 3.5 equivalent sun hours and a 0.75 yield factor produces about 1050 Wh per day, leaving a 150 Wh daily deficit even before any uncounted loads. A larger battery delays depletion but does not remove this persistent deficit. Compare reducing consumption, adding panel area, charging while driving or using an approved shore-power charger. On a shaded campsite, portable panels may find better sunlight than roof panels, but introduce setup, cable and weather-management requirements. Check roof structure, available area, shading from vents and actual payload before choosing rigid or flexible modules. Record the refrigerator mode and seasonal heating-fan demand in the energy table. Finally, verify alternator compatibility and the vehicle manufacturer's restrictions before assuming driving time provides unrestricted charging power.",
    "Presupune consum de 1200 Wh pe zi. Panourile de 400 W, cu 3,5 ore echivalente și factor 0,75, produc orientativ 1050 Wh pe zi. Rămâne deficit de 150 Wh, chiar înainte de sarcini omise. Bateria mai mare amână descărcarea, dar nu elimină deficitul permanent. Compară reducerea consumului, panouri suplimentare, încărcarea la mers sau încărcătorul compatibil de la mal. În camping umbrit, panourile portabile pot găsi soare mai bun, dar cer montaj temporar, cabluri și gestionarea vremii. Verifică structura acoperișului, spațiul, umbra ventilațiilor și masa disponibilă înainte de alegerea panourilor. Notează modul frigiderului și consumul ventilatorului de încălzire iarna. Confirmă compatibilitatea alternatorului și restricțiile vehiculului înainte de a presupune încărcare nelimitată la mers.",
  ),
  "marine-battery-system": b(
    "Prepare separate energy and availability requirements for navigation equipment, communications, bilge systems and comfort loads. For example, a 40 W electronics group operating for ten hours consumes 400 Wh, but its continuity requirement may be more important than its relatively small energy demand. Do not assume an accessory battery bank can replace the engine-starting function. Record what remains powered when a house-bank disconnect is operated and which circuits require a dedicated arrangement under the applicable vessel rules. Salt, vibration, moisture and restricted compartments change the suitability of equipment that looks adequate on paper. Ask for the precise environmental ratings and installation manual, not a general marine marketing label. Shore power adds a separate AC safety and earthing assessment. A vessel specialist should review the combined charging sources and distribution architecture before components are selected as a package.",
    "Separă energia și disponibilitatea cerute de navigație, comunicații, santină și confort. Un grup electronic de 40 W pornit zece ore consumă 400 Wh, dar continuitatea poate conta mai mult decât energia modestă. Bancul de servicii nu înlocuiește automat pornirea motorului. Notează ce rămâne alimentat la deconectarea bancului și ce circuite cer soluție dedicată conform regulilor navei. Sarea, vibrațiile, umezeala și compartimentele înguste schimbă adecvarea unui echipament aparent suficient. Cere valorile exacte de mediu și manualul, nu doar eticheta comercială navală. Alimentarea de la mal adaugă verificare AC și împământare separată. Un specialist al navei trebuie să evalueze sursele de încărcare și distribuția înainte de alegerea pachetului de componente.",
  ),
  "dc-dc-charger-guide": b(
    "An illustrative charger delivering 20 A at 14.4 V supplies 288 W to the battery. If its input is 13 V and efficiency is 90%, input current is approximately 24.6 A, rather than 20 A. This distinction affects the alternator-side cable and available source capacity. In two hours, idealised delivered energy is 576 Wh; tapering, temperature limits and driving conditions can reduce it. If daily demand is 1200 Wh, this charging interval alone is insufficient. A larger charger is only useful when the alternator, battery and wiring can support it continuously. For a combined DC-DC/MPPT unit, read how the two sources share output and whether the PV voltage window fits the array. Prepare separate protection and cable requirements for both source paths. Never infer alternator spare capacity from its headline rating without considering the vehicle's own electrical load.",
    "Un încărcător care livrează 20 A la 14,4 V furnizează 288 W bateriei. La intrare de 13 V și randament de 90%, curentul de intrare este circa 24,6 A, nu 20 A. Diferența contează pentru cablul alternatorului și rezerva sursei. În două ore, energia idealizată este 576 Wh; reducerea curentului, temperatura și mersul pot scădea rezultatul. Pentru consum zilnic de 1200 Wh, intervalul nu ajunge. Încărcătorul mai mare ajută numai dacă alternatorul, bateria și cablurile îl susțin continuu. La DC-DC/MPPT, verifică împărțirea ieșirii și fereastra PV. Pregătește cerințe distincte pentru fiecare cale alimentată. Puterea nominală a alternatorului nu este rezerva disponibilă după consumul vehiculului.",
  ),
  "generator-vs-battery-backup": b(
    "Suppose a battery must recover 2000 Wh while a 500 W essential load remains supplied. A charger delivering an average 1000 W would need at least two hours for the energy alone, with additional allowance for charging behaviour. The generator's AC demand includes charger losses and the simultaneous 500 W load, so a 1000 W generator is not established as sufficient. Check charger input apparent power, power factor and startup behaviour against the generator specification. Compare this arrangement with longer, lower-current charging if fuel use, noise windows or battery limits favour it. Keep combustion equipment outdoors in a location that meets manufacturer and safety guidance, away from openings; enclosure or weather protection must not trap exhaust. The transfer and earthing design remains a qualified installation task. A hybrid system adds flexibility but also introduces more operating states to document and test.",
    "Presupune recuperarea a 2000 Wh în baterie în timp ce un consumator de 500 W rămâne alimentat. Încărcătorul care livrează în medie 1000 W cere minimum două ore numai pentru energie, plus efectul profilului de încărcare. Generatorul susține pierderile încărcătorului și cei 500 W simultani; un generator de 1000 W nu este dovedit suficient. Verifică puterea aparentă, factorul de putere și pornirea încărcătorului. Compară încărcarea mai lentă dacă zgomotul, combustibilul sau bateria o favorizează. Generatorul cu ardere trebuie amplasat afară, departe de deschideri, conform regulilor producătorului și de siguranță. Protecția de ploaie nu trebuie să rețină gazele. Transferul și împământarea cer proiectare calificată. Sistemul hibrid adaugă flexibilitate, dar și stări de funcționare care trebuie documentate și testate.",
  ),
  "ev-charging-basics": b(
    "A vehicle needing 20 kWh of replenishment over an eight-hour parking window requires an average 2.5 kW delivered to its battery, before allowing for charging losses. That energy requirement does not automatically justify installing the fastest available wallbox. Compare the vehicle's AC acceptance, available household capacity, simultaneous heating or cooking loads and the actual parking schedule. A nominal 11 kW three-phase wallbox cannot deliver that output where the supply or vehicle only supports a lower rate. Dynamic load management may help manage a constrained connection, but it must be compatible and correctly commissioned. Existing sockets are not assumed suitable for sustained charging simply because the plug fits. Ask the installer to assess circuit capacity, protection, earthing and cable route against current applicable requirements. Record the agreed charging limit and test the response when other major household loads operate.",
    "Dacă vehiculul trebuie să recupereze 20 kWh în opt ore de staționare, media livrată bateriei este 2,5 kW, înainte de pierderi. Necesarul energetic nu justifică automat cea mai rapidă stație. Compară acceptarea AC a mașinii, capacitatea locuinței, încălzirea sau gătitul simultan și programul real. O stație trifazată nominală de 11 kW nu livrează atât dacă alimentarea sau mașina acceptă mai puțin. Gestionarea dinamică a sarcinii poate ajuta, dar cere compatibilitate și punere în funcțiune corectă. Priza existentă nu este presupusă adecvată încărcării susținute doar fiindcă fișa se potrivește. Instalatorul verifică circuitul, protecția, împământarea și traseul conform cerințelor aplicabile. Notează limita convenită și testează reacția când pornesc alți consumatori mari.",
  ),
  "cable-and-protection-basics": b(
    "A circuit can pass a basic current check and still have unacceptable voltage drop. Consider a long DC cable feeding an inverter: increasing cable length increases resistance and voltage loss, while the inverter may draw more current as its input voltage falls. The return path matters as well as the outgoing conductor. The sizing tool makes its system and length assumptions visible, but installation temperature, grouping, insulation and termination ratings still need assessment. Select protection for the conductor and the possible fault, not merely for the normal appliance power. A nominal 100 A fuse with an unsuitable DC voltage or interrupting rating is not made appropriate by its current label. Record conductor material, route, length convention, installation method and the exact protective-device reference. Ask the installer to verify the weakest terminal or connection as well as the cable itself.",
    "Un circuit poate trece verificarea curentului și totuși avea cădere de tensiune excesivă. La un cablu DC lung spre invertor, lungimea crește rezistența și pierderea, iar invertorul poate cere mai mult curent când tensiunea scade. Contează și întoarcerea, nu doar conductorul de plecare. Calculatorul arată ipotezele sistemului și lungimii, dar temperatura, gruparea, izolația și bornele trebuie evaluate separat. Protecția se alege pentru conductor și defectul posibil, nu doar pentru puterea normală. O siguranță de 100 A cu tensiune DC sau capacitate de rupere nepotrivită nu devine sigură prin eticheta de curent. Notează materialul, traseul, convenția lungimii, montajul și referința protecției. Instalatorul verifică și cea mai slabă bornă sau conexiune.",
  ),
  "industrial-motor-planning": b(
    "For an illustrative 7.5 kW mechanical-output motor on a 400 V three-phase supply, assuming 90% efficiency and 0.80 power factor, running current is approximately 15 A using P / (√3 × V × efficiency × power factor). Replace those assumptions with the nameplate and manufacturer data; the result does not establish starting current or cable protection. Direct-on-line, soft-start and variable-frequency operation create different supply and control requirements. A drive also has input-current, harmonic, cooling and motor-compatibility constraints. For backup planning, decide whether maintaining the control system is sufficient while the large motor remains stopped. That decision can reduce the continuity load substantially, but process and machine-safety requirements govern it. Document the safe state on power loss, permitted restart sequence and who authorises restart. An online current estimate cannot validate protective coordination or the safety of a production machine.",
    "Pentru un motor cu ieșire mecanică de 7,5 kW, alimentare trifazată de 400 V, randament presupus 90% și factor de putere 0,80, curentul este aproximativ 15 A: P / (√3 × V × randament × factor de putere). Înlocuiește ipotezele cu plăcuța și datele producătorului; rezultatul nu stabilește pornirea sau protecția cablului. Pornirea directă, lentă și cu frecvență variabilă cer condiții diferite. Convertizorul are limite de intrare, armonici, răcire și compatibilitate cu motorul. La rezervă, decide dacă este suficientă menținerea comenzilor cu motorul oprit. Poate reduce mult sarcina, dar procesul și siguranța mașinii decid. Documentează starea sigură, secvența și autorizarea repornirii. Estimarea online nu validează coordonarea protecțiilor sau siguranța utilajului.",
  ),
};
