import { bilingual as b } from "./content";
import type { InformationPage } from "./information";
const section = (en: string, ro: string, text: string, translation: string) => ({ title: b(en, ro), body: b(text, translation) });
export const policies: Record<string, InformationPage> = {
  "editorial-policy": {
    title: b("Editorial policy", "Politica editorială"),
    intro: b("How independent equipment research is sourced, checked and maintained.", "Cum documentăm, verificăm și întreținem cercetarea independentă a echipamentelor."),
    sections: [
      section("Evidence before claims", "Dovezi înaintea afirmațiilor", "Use original manufacturer manuals and exact regional model pages for specifications; use identified technical references for equations. Record the URL, model revision and verification date. A supplier link alone does not prove every claim. Unknown fields stay unknown; derived values carry their formula.", "Folosim manuale originale și pagini regionale ale modelului exact pentru specificații, referințe tehnice identificate pentru ecuații. Înregistrăm URL-ul, revizia și data verificării. Un link nu dovedește fiecare afirmație. Datele necunoscute rămân necunoscute; valorile derivate au formulă."),
      section("Human review and current status", "Revizuire umană și stare actuală", "The responsible editor must check sources, arithmetic, limitations and Romanian/English wording before signing a review. Publication or an automated code check is not human technical approval. Pages without a named author or recorded review explicitly show that gap; existing content still requires owner sign-off.", "Editorul responsabil trebuie să verifice sursele, calculele, limitele și textele RO/EN înainte de semnarea revizuirii. Publicarea sau un test automat nu reprezintă aprobare tehnică umană. Paginile fără autor sau revizuire înregistrată indică lipsa; conținutul existent necesită validarea proprietarului."),
      section("Independence", "Independență", "Commission cannot determine a specification, ranking or safety conclusion. Sponsorship and supplied samples must be disclosed beside affected content. We publish no hands-on test claims without actual testing, no paid positive reviews and no invented ratings. Renogy affiliation is not yet approved.", "Comisionul nu poate determina o specificație, clasare sau concluzie de siguranță. Sponsorizările și mostrele se declară lângă conținut. Nu pretindem teste practice inexistente, recenzii pozitive plătite sau evaluări inventate. Afilierea Renogy nu este încă aprobată."),
    ],
  },
  "author-policy": {
    title: b("Author policy", "Politica autorilor"),
    intro: b("Real attribution and declared responsibility, without invented credentials.", "Atribuire reală și responsabilitate declarată, fără acreditări inventate."),
    sections: [section("Identity and scope", "Identitate și competență", "Each authored page needs a real named author, verified biography, relevant expertise and an optional verifiable professional profile. The operator and editor may be different people. Account registration or an expert role does not establish a professional qualification. Missing attribution is shown as pending, not filled with a fictional person.", "Fiecare material necesită un autor real, biografie verificată, competențe relevante și opțional profil profesional verificabil. Operatorul și editorul pot fi persoane diferite. Contul sau rolul de expert nu dovedesc calificarea. Atribuirea lipsă este în așteptare, nu completată cu persoane fictive."), section("Dates and disclosure", "Date și transparență", "Record actual publication and substantive review dates separately. A deployment date is not a review date. Disclose AI assistance, commercial interests and the difference between desk research and hands-on testing. Owners must confirm attribution for each existing page before application.", "Înregistrăm separat publicarea reală și revizuirea substanțială. Data implementării nu este data verificării. Declarăm asistența AI, interesele comerciale și diferența dintre documentare și testare practică. Proprietarul trebuie să confirme atribuirea fiecărei pagini înainte de aplicare.")],
  },
  "corrections-policy": {
    title: b("Corrections policy", "Politica de corecții"),
    intro: b("Report a specific claim so it can be checked against its source.", "Raportează o afirmație concretă pentru verificare față de sursă."),
    sections: [section("Reporting an error", "Raportarea unei erori", "Use Contact with the page URL, disputed statement, exact model and an authoritative source. Do not include passwords, order details or personal documents. Until the private channel is configured, do not post personal information on GitHub. No response time is promised.", "Folosește Contact cu URL-ul paginii, afirmația, modelul exact și sursa autorizată. Nu include parole, detalii de comandă sau documente personale. Până la configurarea canalului privat, nu publica date personale pe GitHub. Nu promitem un termen de răspuns."), section("Review and correction log", "Verificare și jurnal", "The editor should triage safety-relevant errors first, restrict or remove an unsafe claim while checking it, and record substantive corrections with the date, affected text and reason. Correct connected comparisons and calculators where applicable. Cosmetic changes must not refresh technical review dates. No completed corrections are claimed without a record.", "Editorul prioritizează erorile de siguranță, restricționează afirmațiile nesigure în timpul verificării și înregistrează corecțiile substanțiale cu dată, text și motiv. Corectează comparațiile și calculele asociate. Modificările cosmetice nu actualizează data verificării tehnice. Nu declarăm corecții fără înregistrare.")],
  },
  "ai-use-policy": {
    title: b("AI use policy", "Politica de utilizare AI"),
    intro: b("AI can assist drafting and development; it does not certify engineering facts.", "AI poate sprijini redactarea și dezvoltarea; nu certifică informații inginerești."),
    sections: [section("Assistance and accountability", "Asistență și responsabilitate", "AI has assisted website development and editorial drafting. Generated text can contain errors. A named human editor must verify claims and translations against sources before recording technical approval. Automated checks validate software behavior, not professional competence or installation safety.", "AI a asistat dezvoltarea site-ului și redactarea editorială. Textul generat poate conține erori. Un editor uman identificat trebuie să verifice afirmațiile și traducerile înainte de aprobarea tehnică. Testele automate verifică software-ul, nu competența profesională sau siguranța instalației."), section("Boundaries", "Limite", "Sizing tools use explicit deterministic equations rather than asking a language model to invent a result. AI must not invent specifications, sources, qualifications, reviews or affiliate approval. Do not submit confidential material to optional AI tools without authority. Manufacturer manuals and qualified site assessment take precedence over generated suggestions.", "Instrumentele folosesc ecuații deterministe explicite. AI nu trebuie să inventeze specificații, surse, calificări, recenzii sau aprobări de afiliere. Nu trimite materiale confidențiale fără autorizare. Manualele și evaluarea calificată a instalației au prioritate față de sugestiile generate.")],
  },
  "partnerships": {
    title: b("Media kit and partnerships", "Media kit și parteneriate"),
    intro: b("Independent product discovery, comparison and sizing for Romania / EU, in Romanian and English.", "Descoperire, comparație și dimensionare independentă pentru România / UE, în română și engleză."),
    sections: [section("Editorial focus", "Tematică editorială", "Solar panels, LiFePO4 storage, inverters, charging and backup power. We connect original guides, transparent calculators, source-based model comparisons and scenario planning for homes, RVs, marine systems and small businesses. We do not sell equipment or accept product payments.", "Panouri solare, stocare LiFePO4, invertoare, încărcare și rezervă. Conectăm ghiduri originale, calculatoare transparente, comparații documentate și scenarii pentru case, rulote, ambarcațiuni și afaceri mici. Nu vindem echipamente și nu primim plăți pentru produse."), section("Audience evidence", "Dovezi despre audiență", "Data being collected. Verified audience reports are not yet published. Geography, unique visitors, engaged visits, source mix and supplier clicks will be shared only from real, dated analytics exports with the measurement period and consent limitations. Test visits must be excluded. No reach or conversion guarantee is offered.", "Date în curs de colectare. Rapoartele verificate nu sunt încă publicate. Geografia, vizitatorii, vizitele implicate, sursele și clicurile către furnizori vor proveni exclusiv din exporturi reale, datate, cu perioada și limitele consimțământului. Vizitele de test trebuie excluse. Nu garantăm audiență sau conversii."), section("Renogy EU proposal and rules", "Propunere Renogy EU și reguli", "Renogy EU is an intended affiliate target; affiliation not yet approved. We propose relevant educational referrals to the exact EU product pages after approval. No tracking links are active before an actual agreement and approved configuration. The EU campaign identity, eligible countries, domains and promotional terms must be confirmed directly in Impact and with Renogy. A US program page does not establish EU eligibility.", "Renogy EU este vizat pentru afiliere; afilierea nu este încă aprobată. Propunem recomandări educative către paginile EU exacte după aprobare. Urmărirea nu se activează înaintea contractului și configurării aprobate. Identitatea campaniei EU, țările, domeniile și condițiile promoționale necesită confirmare în Impact și cu Renogy. Pagina programului SUA nu stabilește eligibilitatea EU.")],
  },
};
