import { bilingual as b } from "./content";
import type { InformationPage } from "./information";
const section = (en: string, ro: string, text: string, translation: string) => ({ title: b(en, ro), body: b(text, translation) });
export const policies: Record<string, InformationPage> = {
  "editorial-policy": {
    title: b("Editorial policy", "Politica editorială"),
    intro: b("How independent equipment research is sourced, checked and maintained.", "Cum documentăm, verificăm și întreținem cercetarea independentă a echipamentelor."),
    sections: [
      section("Evidence before claims", "Dovezi înaintea afirmațiilor", "Use original manufacturer manuals and exact regional model pages for specifications; use identified technical references for equations. Record the URL, model revision and verification date. A supplier link alone does not prove every claim. Unknown fields stay unknown; derived values carry their formula.", "Folosim manuale originale și pagini regionale ale modelului exact pentru specificații, referințe tehnice identificate pentru ecuații. Înregistrăm URL-ul, revizia și data verificării. Un link nu dovedește fiecare afirmație. Datele necunoscute rămân necunoscute; valorile derivate au formulă."),
      section("Research and technical review", "Documentare și verificare tehnică", "Guides and comparisons use source-based research and explicit calculations. Named authors and human review dates are shown only when documented. Publication and automated software checks do not certify engineering accuracy or installation safety. Use manufacturer documentation and a qualified assessment for final design and installation.", "Ghidurile și comparațiile folosesc documentare pe baza surselor și calcule explicite. Autorii și datele verificărilor umane sunt afișate numai când sunt documentate. Publicarea și testele automate nu certifică exactitatea inginerească sau siguranța instalației. Folosește documentația producătorului și evaluarea calificată pentru proiectare și montaj."),
      section("Independence", "Independență", "Commission cannot determine a specification, ranking or safety conclusion. Sponsorship and supplied samples must be disclosed beside affected content. We publish no hands-on test claims without actual testing, no paid positive reviews and no invented ratings. Renogy affiliation is not yet approved.", "Comisionul nu poate determina o specificație, clasare sau concluzie de siguranță. Sponsorizările și mostrele se declară lângă conținut. Nu pretindem teste practice inexistente, recenzii pozitive plătite sau evaluări inventate. Afilierea Renogy nu este încă aprobată."),
    ],
  },
  "author-policy": {
    title: b("Author policy", "Politica autorilor"),
    intro: b("Real attribution and declared responsibility, without invented credentials.", "Atribuire reală și responsabilitate declarată, fără acreditări inventate."),
    sections: [section("Identity and scope", "Identitate și competență", "Author bylines identify documented contributors. Publisher ownership is separate from authorship and technical review; it does not establish professional qualifications. We publish biographies and relevant expertise only when confirmed, and do not assign an author or reviewer to content without evidence.", "Atribuirile identifică autori documentați. Proprietatea platformei este distinctă de autorat și verificarea tehnică; nu dovedește calificări profesionale. Publicăm biografii și competențe relevante numai când sunt confirmate și nu atribuim autori sau verificatori fără dovezi."), section("Dates and disclosure", "Date și transparență", "Publication and substantive review dates are recorded separately when supported by editorial records. A deployment date is not a review date. We disclose AI assistance and commercial interests, and distinguish source-based research from hands-on testing. Content without an explicit human review date carries no claim of completed human technical review.", "Datele publicării și revizuirii substanțiale sunt înregistrate separat, pe baza evidențelor editoriale. Data implementării nu este data verificării. Declarăm asistența AI și interesele comerciale și distingem documentarea de testarea practică. Un material fără dată explicită de verificare umană nu pretinde o verificare tehnică umană finalizată.")],
  },
  "corrections-policy": {
    title: b("Corrections policy", "Politica de corecții"),
    intro: b("Report a specific claim so it can be checked against its source.", "Raportează o afirmație concretă pentru verificare față de sursă."),
    sections: [section("Reporting an error", "Raportarea unei erori", "Email contact@mairelectroai.com with the page URL, disputed statement, exact model and an authoritative source. Do not include passwords, order details or personal documents. GitHub is also available for public technical issues; never post personal information there. No response time is promised.", "Scrie la contact@mairelectroai.com cu URL-ul paginii, afirmația, modelul exact și sursa autorizată. Nu include parole, detalii de comandă sau documente personale. GitHub este disponibil și pentru probleme tehnice publice; nu publica acolo date personale. Nu promitem un termen de răspuns."), section("Review and correction log", "Verificare și jurnal", "Safety-relevant reports take priority in the correction process. A claim may be restricted or removed while it is checked. Substantive corrections are recorded with their date and reason, including related comparisons or calculations where applicable. Cosmetic changes do not refresh technical review dates.", "Sesizările privind siguranța au prioritate în procesul de corectare. O afirmație poate fi restricționată sau eliminată în timpul verificării. Corecțiile substanțiale sunt înregistrate cu dată și motiv, inclusiv în comparațiile sau calculele asociate. Modificările cosmetice nu actualizează data verificării tehnice.")],
  },
  "ai-use-policy": {
    title: b("AI use policy", "Politica de utilizare AI"),
    intro: b("AI can assist drafting and development; it does not certify engineering facts.", "AI poate sprijini redactarea și dezvoltarea; nu certifică informații inginerești."),
    sections: [section("Assistance and accountability", "Asistență și responsabilitate", "AI has assisted website development and editorial drafting. Generated text can contain errors. A named human editor must verify claims and translations against sources before recording technical approval. Automated checks validate software behavior, not professional competence or installation safety.", "AI a asistat dezvoltarea site-ului și redactarea editorială. Textul generat poate conține erori. Un editor uman identificat trebuie să verifice afirmațiile și traducerile înainte de aprobarea tehnică. Testele automate verifică software-ul, nu competența profesională sau siguranța instalației."), section("Boundaries", "Limite", "Sizing tools use explicit deterministic equations rather than asking a language model to invent a result. AI must not invent specifications, sources, qualifications, reviews or affiliate approval. Do not submit confidential material to optional AI tools without authority. Manufacturer manuals and qualified site assessment take precedence over generated suggestions.", "Instrumentele folosesc ecuații deterministe explicite. AI nu trebuie să inventeze specificații, surse, calificări, recenzii sau aprobări de afiliere. Nu trimite materiale confidențiale fără autorizare. Manualele și evaluarea calificată a instalației au prioritate față de sugestiile generate.")],
  },
  "partnerships": {
    title: b("Media kit and partnerships", "Media kit și parteneriate"),
    intro: b("Independent product discovery, comparison and sizing for Romania / EU, in Romanian and English.", "Descoperire, comparație și dimensionare independentă pentru România / UE, în română și engleză."),
    sections: [section("Editorial focus", "Tematică editorială", "Solar panels, LiFePO4 storage, inverters, charging and backup power. We connect original guides, transparent calculators, source-based model comparisons and scenario planning for homes, RVs, marine systems and small businesses. We do not sell equipment or accept product payments.", "Panouri solare, stocare LiFePO4, invertoare, încărcare și rezervă. Conectăm ghiduri originale, calculatoare transparente, comparații documentate și scenarii pentru case, rulote, ambarcațiuni și afaceri mici. Nu vindem echipamente și nu primim plăți pentru produse."), section("Audience evidence", "Dovezi despre audiență", "No verified audience figures are published. Any audience report supplied to a prospective partner will use real, dated analytics exports with the measurement period and consent limitations. Test visits are excluded from audience evidence. We offer no reach or conversion guarantee.", "Nu sunt publicate cifre de audiență verificate. Orice raport oferit unui potențial partener va folosi exporturi reale, datate, cu perioada măsurării și limitele consimțământului. Vizitele de test sunt excluse din dovezile despre audiență. Nu garantăm audiență sau conversii."), section("Renogy EU proposal and rules", "Propunere Renogy EU și reguli", "Renogy EU is an intended affiliate target; affiliation not yet approved. We propose relevant educational referrals to the exact EU product pages after approval. No tracking links are active before an actual agreement and approved configuration. The EU campaign identity, eligible countries, domains and promotional terms must be confirmed directly in Impact and with Renogy. A US program page does not establish EU eligibility.", "Renogy EU este vizat pentru afiliere; afilierea nu este încă aprobată. Propunem recomandări educative către paginile EU exacte după aprobare. Urmărirea nu se activează înaintea contractului și configurării aprobate. Identitatea campaniei EU, țările, domeniile și condițiile promoționale necesită confirmare în Impact și cu Renogy. Pagina programului SUA nu stabilește eligibilitatea EU.")],
  },
};
