import { PlatformShell } from "@/components/platform-shell";
import { DataDisclaimer, HeroMapPreview, ProductCtas } from "@/components/power/marketing";

export default function Home() {
  return (
    <PlatformShell prioritizeBackground contentClassName="flex-1 px-4 pb-16 pt-10 sm:px-6 lg:px-8">
      <div className="mx-auto flex w-full max-w-6xl flex-col gap-16 text-slate-800"><section className="grid items-center gap-10 lg:grid-cols-2"><div><p className="eyebrow">Global Power Resilience Map</p><h1 className="mt-4 text-5xl font-bold tracking-tight text-slate-950 sm:text-6xl">Know where power is stable.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Explore power plants, grid conditions and regional electricity resilience across the world.</p><ProductCtas/></div><HeroMapPreview/></section><section className="grid gap-4 md:grid-cols-3">{[["Global infrastructure visibility", "Find available power-facility information across countries and regions."], ["Regional power resilience", "Read estimated stability alongside confidence and data freshness."], ["Alerts and comparison", "Compare locations and prepare monitored locations when the backend is connected."]].map(([title, body]) => <article key={title} className="info-card"><h2>{title}</h2><p>{body}</p></article>)}</section><section className="grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">How it works</p><ol className="mt-4 space-y-3 text-slate-700">{["Choose a country, region or city.", "Review available power infrastructure.", "Examine stability indicators and data confidence.", "Save locations and create alerts."].map((item, index) => <li key={item} className="flex gap-3"><b className="text-teal-700">0{index + 1}</b>{item}</li>)}</ol></div><div className="info-card"><p className="eyebrow">Example comparison</p><h2 className="mt-3">Constanța · Warsaw · Valencia</h2><p>Use the comparison workspace to evaluate stability, generation diversity, freshness and confidence side by side.</p></div></section><DataDisclaimer/></div>
    </PlatformShell>
  );
}
