"use client";

import Link from "next/link";
import { useState } from "react";
import type { Locale } from "@/lib/i18n/types";

export function DiagnosticFlow({ locale }: { locale: Locale }) {
  const uk = locale === "uk";
  const c = uk ? { eyebrow: "Діагностика", title: "Що не працює?", intro: "Оберіть обладнання та опишіть симптом. Ми покажемо безпечні первинні перевірки й межу, де потрібен кваліфікований електрик.", categories: ["Інвертор", "Акумулятор", "Сонячні панелі", "Генератор", "UPS / ДБЖ", "Домашня електромережа", "Автомат / ПЗВ", "Електродвигун", "EV charger", "Інше обладнання"], issue: "Що сталося?", issues: ["Не запускається", "Немає вихідної напруги", "Вимикається під навантаженням", "Не заряджає акумулятор", "Не бачить мережу", "Перегрівається", "Показує помилку", "Працює нестабільно"], code: "Код помилки (необов’язково)", start: "Почати безпечну перевірку", result: "Результат первинної діагностики", causes: "Можливі причини", safe: "Безпечні перевірки для користувача", pro: "Потрібен кваліфікований електрик", danger: "НЕБЕЗПЕЧНО — не відкривайте щити під напругою, не обходьте захисти й не з’єднуйте генератор із мережею зворотним живленням.", ai: "Запитати Electro-AI", knowledge: "Відкрити статті з діагностики", reset: "Почати спочатку" } : { eyebrow: "Diagnostics", title: "What is not working?", intro: "Choose equipment and describe the symptom. We show safe first checks and the point where a qualified electrician is needed.", categories: ["Inverter", "Battery", "Solar panels", "Generator", "UPS", "Home electrical system", "Breaker / RCD", "Electric motor", "EV charger", "Other equipment"], issue: "What happened?", issues: ["Will not start", "No output voltage", "Shuts down under load", "Does not charge battery", "Cannot see grid", "Overheats", "Shows an error", "Operates unstably"], code: "Fault code (optional)", start: "Start safe check", result: "Initial diagnostic result", causes: "Possible causes", safe: "Safe user checks", pro: "Qualified electrician required", danger: "DANGER — do not open energized distribution boards, bypass protective devices, or backfeed a generator into the grid.", ai: "Ask Electro-AI", knowledge: "Open diagnostic articles", reset: "Start over" };
  const [category, setCategory] = useState<string | null>(null); const [issue, setIssue] = useState<string | null>(null); const [code, setCode] = useState(""); const [done, setDone] = useState(false);
  if (done && category && issue) return <section className="mx-auto max-w-4xl space-y-5"><div className="brand-glass-card rounded-3xl p-6"><p className="eyebrow">{c.eyebrow}</p><h1 className="mt-3 text-3xl font-bold text-slate-950">{c.result}</h1><p className="mt-3 text-slate-700">{category} · {issue}{code ? ` · ${code}` : ""}</p></div><div className="grid gap-4 md:grid-cols-2"><article className="info-card rounded-3xl p-5"><h2 className="font-bold text-slate-950">{c.causes}</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-slate-700"><li>{uk ? "Низька напруга акумулятора або втрата зв’язку з BMS — висока ймовірність." : "Battery undervoltage or BMS communication loss — high probability."}</li><li>{uk ? "Перевантаження або пусковий струм — середня ймовірність." : "Overload or inrush current — medium probability."}</li><li>{uk ? "Неправильні налаштування або несправність обладнання — потребує підтвердження." : "Incorrect settings or equipment fault — requires confirmation."}</li></ol></article><article className="info-card rounded-3xl p-5"><h2 className="font-bold text-slate-950">{c.safe}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-700"><li>{uk ? "Перевірте індикатори, повідомлення на екрані та стан заряду без відкривання корпусу." : "Check indicators, display messages, and charge status without opening enclosures."}</li><li>{uk ? "Від’єднайте некритичні навантаження штатними вимикачами." : "Disconnect non-essential loads using normal controls."}</li><li>{uk ? "Зіставте код помилки з інструкцією виробника." : "Match the fault code to the manufacturer manual."}</li></ul></article></div><p className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-950">{c.danger}</p><div className="flex flex-wrap gap-3"><Link className="button-primary" href="/assistant">{c.ai}</Link><Link className="button-outline" href="/knowledge-base">{c.knowledge}</Link><button type="button" className="button-outline" onClick={() => { setDone(false); setCategory(null); setIssue(null); setCode(""); }}>{c.reset}</button></div></section>;
  return <section className="mx-auto max-w-4xl space-y-5"><div className="brand-glass-card rounded-3xl p-6"><p className="eyebrow">{c.eyebrow}</p><h1 className="mt-3 text-3xl font-bold text-slate-950">{c.title}</h1><p className="mt-3 text-slate-700">{c.intro}</p></div><div className="info-card rounded-3xl p-6"><div className="grid gap-2 sm:grid-cols-2">{c.categories.map((item) => <button type="button" key={item} onClick={() => setCategory(item)} className={`rounded-xl border p-3 text-left font-semibold ${category === item ? "border-teal-500 bg-teal-50" : "border-slate-200 bg-white"}`}>{item}</button>)}</div>{category ? <><h2 className="mt-6 font-bold text-slate-950">{c.issue}</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{c.issues.map((item) => <button type="button" key={item} onClick={() => setIssue(item)} className={`rounded-xl border p-3 text-left text-sm ${issue === item ? "border-teal-500 bg-teal-50" : "border-slate-200 bg-white"}`}>{item}</button>)}</div><input value={code} onChange={(event) => setCode(event.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 bg-white p-3" placeholder={c.code} />{issue ? <button type="button" className="button-primary mt-4" onClick={() => setDone(true)}>{c.start}</button> : null}</> : null}</div></section>;
}
