"use client";

import { useEffect, useMemo, useRef, useState } from "react";

import type { Locale } from "@/lib/i18n/types";

type LocalDocument = { id: string; name: string; type: string; size: number; remote?: boolean };
const allowed = ["application/pdf", "image/jpeg", "image/png", "image/webp", "text/plain", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];

export function DocumentsWorkspace({ locale }: { locale: Locale }) {
  const uk = locale === "uk";
  const copy = uk ? {
    eyebrow: "Documents AI", title: "Робочий простір технічної документації", description: "Завантажуйте інструкції, схеми, звіти та фото обладнання. Авторизовані користувачі зберігають документи в захищеному сховищі свого облікового запису.", upload: "Завантажити документ", drop: "Перетягніть файли сюди або оберіть їх", types: "PDF, JPG, PNG, WEBP, TXT або DOCX", empty: "Документів поки немає.", emptyDescription: "Завантажте інструкцію, схему, технічний паспорт або звіт, щоб використовувати їх у діагностиці.", search: "Пошук у списку документів", actions: "Дії з документом", summary: "Підсумувати", explain: "Пояснити", specs: "Знайти характеристики", fault: "Знайти код помилки", diagnostics: "Використати в діагностиці", ai: "Запитати Electro-AI", remove: "Видалити", selected: "Вибраний документ", noExtraction: "Автоматичне вилучення даних не виконано: для цього потрібен підключений серверний parser. Не вигадуємо характеристик або посилань на сторінки.", local: "Збережено", invalid: "Підтримуються лише PDF, зображення, TXT і DOCX.", login: "Увійдіть, щоб зберігати документи у своєму обліковому записі." } : {
    eyebrow: "Documents AI", title: "Technical document workspace", description: "Upload manuals, diagrams, reports, and equipment photos. Authenticated users save documents in their protected account storage.", upload: "Upload document", drop: "Drop files here or choose files", types: "PDF, JPG, PNG, WEBP, TXT or DOCX", empty: "No documents yet.", emptyDescription: "Upload a manual, schematic, datasheet, or report to use it in diagnostics.", search: "Search document list", actions: "Document actions", summary: "Summarize", explain: "Explain", specs: "Find specification", fault: "Find fault code", diagnostics: "Use for diagnostics", ai: "Ask Electro-AI", remove: "Remove", selected: "Selected document", noExtraction: "No automated extraction has run: a server-side parser is required. Specifications and page citations are never invented.", local: "Saved", invalid: "Only PDF, image, TXT, and DOCX files are supported.", login: "Sign in to save documents to your account." };
  const input = useRef<HTMLInputElement>(null);
  const [documents, setDocuments] = useState<LocalDocument[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  const selected = documents.find((item) => item.id === selectedId) ?? null;
  const visible = useMemo(() => documents.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())), [documents, query]);
  useEffect(() => { fetch("/api/documents").then(async (response) => { if (response.status === 401) return; const body = await response.json(); if (response.ok) setDocuments(body.documents.map((item: { id: string; name: string; mime_type: string; byte_size: number }) => ({ id: item.id, name: item.name, type: item.mime_type, size: item.byte_size, remote: true }))); }).catch(() => {}); }, []);
  const addFiles = async (files: FileList | null) => { if (!files) return; const valid = Array.from(files).filter((file) => allowed.includes(file.type) || /\.(pdf|jpe?g|png|webp|txt|docx)$/i.test(file.name)); if (valid.length !== files.length) setNotice(copy.invalid); for (const file of valid) { const form = new FormData(); form.append("file", file); const response = await fetch("/api/documents", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) { setNotice(response.status === 401 ? copy.login : body.error); continue; } const item = body.document; setDocuments((current) => [{ id: item.id, name: item.name, type: item.mime_type, size: item.byte_size, remote: true }, ...current]); setSelectedId(item.id); } };
  const removeSelected = async () => { if (!selected) return; const response = await fetch("/api/documents", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: selected.id }) }); if (!response.ok) { const body = await response.json(); setNotice(body.error); return; } setDocuments((items) => items.filter((item) => item.id !== selected.id)); setSelectedId(null); };
  return <section className="mx-auto w-full max-w-7xl space-y-6"><div className="brand-glass-card rounded-[2rem] p-6 sm:p-8"><p className="eyebrow">{copy.eyebrow}</p><h1 className="mt-3 text-3xl font-bold text-slate-950 sm:text-5xl">{copy.title}</h1><p className="mt-4 max-w-3xl text-slate-700">{copy.description}</p></div><div className="grid gap-5 lg:grid-cols-[.8fr_1.4fr_.9fr]"><aside className="info-card rounded-3xl p-4"><button type="button" className="button-primary w-full" onClick={() => input.current?.click()}>{copy.upload}</button><input ref={input} className="sr-only" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp,.txt,.docx" onChange={(event) => addFiles(event.target.files)} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm" placeholder={copy.search} />{notice ? <p className="mt-3 text-sm text-amber-800">{notice}</p> : null}<div className="mt-4 space-y-2">{visible.map((item) => <button type="button" key={item.id} onClick={() => setSelectedId(item.id)} className={`w-full rounded-xl border p-3 text-left text-sm ${selectedId === item.id ? "border-teal-400 bg-teal-50" : "border-slate-200 bg-white"}`}><b className="block truncate">{item.name}</b><span className="text-slate-500">{Math.ceil(item.size / 1024)} KB · {copy.local}</span></button>)}</div></aside><main className="info-card min-h-80 rounded-3xl p-6"><div onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); addFiles(event.dataTransfer.files); }} className="flex min-h-64 flex-col items-center justify-center rounded-2xl border-2 border-dashed border-teal-200 bg-teal-50/40 p-8 text-center"><p className="font-semibold text-slate-900">{selected ? selected.name : copy.empty}</p><p className="mt-2 max-w-md text-sm text-slate-600">{selected ? `${selected.type || "file"} · ${Math.ceil(selected.size / 1024)} KB` : copy.emptyDescription}</p><p className="mt-4 text-xs text-slate-500">{copy.drop}<br />{copy.types}</p></div></main><aside className="info-card rounded-3xl p-5"><h2 className="font-bold text-slate-950">{copy.selected}</h2>{selected ? <><p className="mt-2 break-all text-sm text-slate-600">{selected.name}</p><div className="mt-5 grid gap-2">{[copy.summary, copy.explain, copy.specs, copy.fault, copy.diagnostics, copy.ai].map((action) => <button type="button" key={action} onClick={() => setNotice(`${action}: ${copy.noExtraction}`)} className="button-outline text-left">{action}</button>)}</div><button type="button" onClick={removeSelected} className="mt-4 text-sm font-semibold text-rose-700">{copy.remove}</button></> : <p className="mt-3 text-sm text-slate-600">{copy.emptyDescription}</p>}<p className="mt-5 rounded-xl bg-amber-50 p-3 text-xs text-amber-950">{copy.noExtraction}</p></aside></div></section>;
}
