"use client";
import { useState } from "react";
import type { Locale } from "@/lib/i18n/types";

export function ElectroAiChat({ locale, configured }: { locale: Locale; configured: boolean }) {
  const uk = locale === "uk";
  const c = uk ? { eyebrow: "Electro-AI", title: "Електротехнічний помічник із контекстом", intro: "Оберіть режим, додайте технічне запитання або код помилки. Electro-AI не замінює кваліфікованого електрика для небезпечних робіт.", modes: ["Енергетика дому", "Діагностика несправності", "Підібрати обладнання", "Розрахувати систему", "Пояснити документ", "Електротехнічне питання", "Для бізнесу", "Professional / Engineering"], placeholder: "Наприклад: інвертор вимикається під навантаженням, код F56…", send: "Надіслати запит", unavailable: "AI-провайдер не налаштований. Додайте OPENAI_API_KEY і OPENAI_MODEL у змінні середовища для реальних відповідей.", error: "Не вдалося отримати відповідь. Спробуйте пізніше." } : { eyebrow: "Electro-AI", title: "Electrical assistant with context", intro: "Choose a mode and add a technical question or fault code. Electro-AI does not replace a qualified electrician for hazardous work.", modes: ["Home Energy", "Diagnostics", "Select Equipment", "Design System", "Explain Document", "Electrical Question", "Business", "Professional / Engineering"], placeholder: "For example: inverter shuts down under load, code F56…", send: "Send request", unavailable: "AI provider is not configured. Add OPENAI_API_KEY and OPENAI_MODEL to environment variables for real responses.", error: "Could not get an answer. Try again later." };
  const [mode, setMode] = useState(c.modes[0]); const [prompt, setPrompt] = useState(""); const [answer, setAnswer] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!configured || !prompt.trim()) return; setLoading(true); setAnswer(""); try { const response = await fetch("/api/ai", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt, mode, locale }) }); const body = await response.json(); setAnswer(response.ok ? body.answer : body.error); } catch { setAnswer(c.error); } finally { setLoading(false); } };
  return <section className="mx-auto max-w-5xl space-y-5"><div className="brand-glass-card rounded-3xl p-6"><p className="eyebrow">{c.eyebrow}</p><h1 className="mt-3 text-3xl font-bold text-slate-950 sm:text-5xl">{c.title}</h1><p className="mt-4 text-slate-700">{c.intro}</p></div><form onSubmit={submit} className="info-card rounded-3xl p-6"><div className="flex flex-wrap gap-2">{c.modes.map((item) => <button type="button" key={item} onClick={() => setMode(item)} className={`rounded-full border px-3 py-2 text-sm ${mode === item ? "border-teal-500 bg-teal-50" : "border-slate-200 bg-white"}`}>{item}</button>)}</div><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} className="mt-5 min-h-36 w-full rounded-2xl border border-slate-200 bg-white p-4" placeholder={c.placeholder} disabled={!configured} /><button type="submit" className="button-primary mt-4" disabled={!configured || loading}>{loading ? "…" : c.send}</button>{!configured ? <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-950">{c.unavailable}</p> : null}{answer ? <article className="mt-5 rounded-2xl bg-teal-50 p-5 whitespace-pre-wrap text-slate-800">{answer}</article> : null}</form></section>;
}
