import Link from "next/link";
import { PlatformShell } from "@/components/platform-shell";
import { AffiliateDisclosure } from "@/components/marketplace/affiliate-disclosure";
import { ProductCard } from "@/components/marketplace/product-card";
import { catalog, marketplaceCategories } from "@/lib/affiliate/catalog";
import { buildMetadata } from "@/lib/metadata";

export const metadata = buildMetadata({ title: "Energy Marketplace", description: "Calculate, compare and choose electrical and energy solutions before visiting approved external sellers.", path: "/marketplace" });

export default async function MarketplacePage({ searchParams }: { searchParams: Promise<{ batteryKwh?: string; inverterKw?: string; surgeKw?: string; region?: string }> }) {
  const requirements = await searchParams;
  const hasRequirements = requirements.batteryKwh || requirements.inverterKw || requirements.surgeKw;
  const featured = catalog.filter((product) => product.featured);
  return <PlatformShell><main className="mx-auto w-full max-w-6xl space-y-12">{hasRequirements ? <section className="rounded-3xl border border-lime-100/30 bg-lime-100/[.1] p-6 text-white"><p className="eyebrow">Calculator recommendation received</p><h2 className="mt-2 text-2xl font-bold">Start with equipment classes that fit your calculated requirement</h2><p className="mt-3 text-white/75">Region: {requirements.region ?? "EU"} · Battery: {requirements.batteryKwh ?? "—"} kWh · Inverter continuous: {requirements.inverterKw ?? "—"} kW · Surge: {requirements.surgeKw ?? "—"} kW. These are planning inputs, not a final design.</p><div className="mt-4 flex gap-3"><Link href="/marketplace/category/lithium-batteries" className="button-primary">Review batteries</Link><Link href="/marketplace/category/inverters" className="button-outline">Review inverters</Link></div></section> : null}<section className="brand-glass-card rounded-[2rem] p-7 sm:p-10"><p className="eyebrow">M Air Energy Marketplace</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-tight text-white sm:text-6xl">Find the right electrical and energy solution—not just another product.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">Calculate, compare and understand your system before continuing to an approved external merchant.</p><div className="mt-7 flex flex-wrap gap-3"><Link className="button-primary" href="/marketplace/find-my-solution">Find My Solution</Link><a className="button-outline" href="#products">Browse products</a></div><div className="mt-6 max-w-2xl"><AffiliateDisclosure /></div></section><section><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Choose a category</p><h2 className="mt-2 text-3xl font-bold text-white">Start with the system component</h2></div><Link href="/marketplace/find-my-solution" className="text-sm font-semibold text-lime-100">Need guidance? →</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{marketplaceCategories.map((category) => <Link key={category.slug} href={`/marketplace/category/${category.slug}`} className="brand-glass-card rounded-2xl p-5 transition hover:-translate-y-1"><span className="text-3xl text-lime-100">{category.icon}</span><h3 className="mt-4 font-semibold text-white">{category.name}</h3><p className="mt-2 text-sm leading-6 text-white/65">{category.summary}</p></Link>)}</div></section><section id="products"><p className="eyebrow">Partner product categories</p><h2 className="mt-2 text-3xl font-bold text-white">Curated, replaceable catalog data</h2><p className="mt-3 max-w-3xl text-white/70">These neutral category records are not live inventory, stock claims or copied merchant listings. Product pages link to the partner for current details.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featured.map((product) => <ProductCard key={product.id} product={product}/>)}</div></section></main></PlatformShell>;
}
