import Link from "next/link";
import { PlatformShell } from "@/components/platform-shell";
import { AffiliateDisclosure } from "@/components/marketplace/affiliate-disclosure";
import { ProductCard } from "@/components/marketplace/product-card";
import { catalog, marketplaceCategories } from "@/lib/affiliate/catalog";
import { buildMetadata } from "@/lib/metadata";
import { getRequestDictionary } from "@/lib/i18n/request";

export const metadata = buildMetadata({ title: "Energy Marketplace", description: "Calculate, compare and choose electrical and energy solutions before visiting approved external sellers.", path: "/marketplace" });

export default async function MarketplacePage({ searchParams }: { searchParams: Promise<{ batteryKwh?: string; inverterKw?: string; surgeKw?: string; region?: string }> }) {
  const requirements = await searchParams;
  const hasRequirements = requirements.batteryKwh || requirements.inverterKw || requirements.surgeKw;
  const featured = catalog.filter((product) => product.featured);
  const t = await getRequestDictionary();
  return <PlatformShell><main className="mx-auto w-full max-w-6xl space-y-12">{hasRequirements ? <section className="rounded-3xl border border-lime-100/30 bg-lime-100/[.1] p-6 text-white"><p className="eyebrow">{t["marketplace.page.received"]}</p><h2 className="mt-2 text-2xl font-bold">{t["marketplace.page.requirements"]}</h2><p className="mt-3 text-white/75">Region: {requirements.region ?? "EU"} · Battery: {requirements.batteryKwh ?? "—"} kWh · Inverter continuous: {requirements.inverterKw ?? "—"} kW · Surge: {requirements.surgeKw ?? "—"} kW. {t["marketplace.page.inputs"]}</p><div className="mt-4 flex gap-3"><Link href="/marketplace/category/lithium-batteries" className="button-primary">{t["marketplace.page.batteries"]}</Link><Link href="/marketplace/category/inverters" className="button-outline">{t["marketplace.page.inverters"]}</Link></div></section> : null}<section className="brand-glass-card rounded-[2rem] p-7 sm:p-10"><p className="eyebrow">{t["marketplace.eyebrow"]}</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-tight text-white sm:text-6xl">{t["marketplace.page.hero"]}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">{t["marketplace.page.heroDescription"]}</p><div className="mt-7 flex flex-wrap gap-3"><Link className="button-primary" href="/marketplace/find-my-solution">{t["marketplace.page.find"]}</Link><a className="button-outline" href="#products">{t["marketplace.page.browse"]}</a></div><div className="mt-6 max-w-2xl"><AffiliateDisclosure dictionary={t}/></div></section><section><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">{t["marketplace.page.choose"]}</p><h2 className="mt-2 text-3xl font-bold text-white">{t["marketplace.page.component"]}</h2></div><Link href="/marketplace/find-my-solution" className="text-sm font-semibold text-lime-100">{t["marketplace.page.guidance"]}</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{marketplaceCategories.map((category) => <Link key={category.slug} href={`/marketplace/category/${category.slug}`} className="brand-glass-card rounded-2xl p-5 transition hover:-translate-y-1"><span className="text-3xl text-lime-100">{category.icon}</span><h3 className="mt-4 font-semibold text-white">{category.name}</h3><p className="mt-2 text-sm leading-6 text-white/65">{category.summary}</p></Link>)}</div></section><section id="products"><p className="eyebrow">{t["marketplace.page.partnerCategories"]}</p><h2 className="mt-2 text-3xl font-bold text-white">{t["marketplace.page.catalog"]}</h2><p className="mt-3 max-w-3xl text-white/70">{t["marketplace.page.catalogDescription"]}</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featured.map((product) => <ProductCard key={product.id} product={product} dictionary={t}/>)}</div></section></main></PlatformShell>;
}
