import { renogyEu } from "@/lib/affiliate/providers/renogy";
import type { CatalogProduct, MarketplaceRegion, ProductCategory } from "@/lib/affiliate/types";
const date = "2026-08-12";
const eu = (input: Omit<CatalogProduct, "affiliateUrl" | "merchant" | "merchantRegion" | "lastUpdated" | "availability" | "image" | "whyRecommended">): CatalogProduct => ({ ...input, whyRecommended: "This neutral planning category matches the calculated component role. Confirm the final product against the full system design.", image: null, merchant: "Renogy EU (reference supplier)", merchantRegion: "EU", availability: "partner-check", lastUpdated: date, affiliateUrl: renogyEu.buildAffiliateUrl(input.productUrl) });
export const marketplaceCategories: { slug: ProductCategory; name: string; summary: string; icon: string }[] = [
  { slug: "solar-panels", name: "Solar panels", summary: "Generation for home, mobile and off-grid systems.", icon: "☀" }, { slug: "lithium-batteries", name: "Lithium batteries", summary: "Storage sized around usable energy, not guesswork.", icon: "▣" }, { slug: "inverters", name: "Inverters", summary: "Convert stored DC power into dependable AC loads.", icon: "↯" }, { slug: "backup-power", name: "Backup power", summary: "Integrated systems for essential circuits.", icon: "◉" }, { slug: "solar-kits", name: "Solar kits", summary: "Matched starting points for common applications.", icon: "⌁" }, { slug: "charge-controllers", name: "Charge controllers", summary: "Protect and optimise solar charging.", icon: "◌" }, { slug: "electrical-accessories", name: "Electrical accessories", summary: "Wiring, protection and monitoring essentials.", icon: "⌘" }, { slug: "industrial-electrical", name: "Industrial electrical", summary: "Components for professional electrical work.", icon: "▤" },
  { slug: "marine-electrical", name: "Marine electrical", summary: "DC power, charging and protection for vessel-specific systems.", icon: "⚓" },
];
export const catalog: CatalogProduct[] = [
  eu({ id: "battery-lfp-100", slug: "lfp-battery-12v-100ah", brand: "Curated category", name: "12 V 100 Ah LiFePO₄ battery", category: "lithium-batteries", description: "Representative storage category for compact backup and mobile systems.", price: null, currency: "EUR", originalPrice: null, productUrl: "https://eu.renogy.com/collections/lithium-batteries", technicalSpecs: { Chemistry: "LiFePO₄", "Nominal voltage": "12 V", "Planning capacity": "100 Ah", "Use case": "Mobile / compact backup" }, tags: ["battery", "backup", "rv"], featured: true, recommendedFor: ["RV / caravan", "Small essential-load backup"], compatibilityNotes: "Confirm BMS limits, inverter surge demand, charging profile and installation requirements before purchase." }),
  eu({ id: "inverter-2000", slug: "pure-sine-inverter-2000w", brand: "Curated category", name: "2,000 W pure sine inverter", category: "inverters", description: "Representative inverter category for medium essential-load systems.", price: null, currency: "EUR", originalPrice: null, productUrl: "https://eu.renogy.com/collections/inverters", technicalSpecs: { "Continuous output": "2,000 W class", Waveform: "Pure sine", "System planning": "12 V or 24 V", "Use case": "Essential AC loads" }, tags: ["inverter", "backup", "off-grid"], featured: true, recommendedFor: ["Home backup", "Off-grid cabin"], compatibilityNotes: "Select DC voltage, cable protection and surge rating from a complete system design." }),
  eu({ id: "solar-kit-400", slug: "portable-solar-kit-400w", brand: "Curated category", name: "400 W portable solar kit", category: "solar-kits", description: "Representative portable generation category for RV and off-grid use.", price: null, currency: "EUR", originalPrice: null, productUrl: "https://eu.renogy.com/collections/solar-kits", technicalSpecs: { "Array class": "400 W", Format: "Portable / roof-mount planning", "Controller": "Required", "Use case": "Mobile solar" }, tags: ["solar", "rv", "kit"], featured: true, recommendedFor: ["RV / caravan", "Portable off-grid"], compatibilityNotes: "Solar yield depends on climate, orientation, shading and controller/battery compatibility." }),
  eu({ id: "controller-mppt", slug: "mppt-charge-controller", brand: "Curated category", name: "MPPT solar charge controller", category: "charge-controllers", description: "Representative MPPT controller category for matched solar and battery systems.", price: null, currency: "EUR", originalPrice: null, productUrl: "https://eu.renogy.com/collections/solar-charge-controllers", technicalSpecs: { Type: "MPPT", "Battery chemistry": "System dependent", "PV input": "System dependent", "Use case": "Solar charging" }, tags: ["solar", "controller", "mppt"], featured: false, recommendedFor: ["Off-grid cabin", "Solar retrofit"], compatibilityNotes: "Confirm PV open-circuit voltage and charge current ratings before selecting a controller." }),
  eu({ id: "marine-dc", slug: "marine-dc-power-system", brand: "Curated category", name: "Marine DC power system components", category: "marine-electrical", description: "A structured category for marine battery, charging and DC distribution planning.", price: null, currency: "EUR", originalPrice: null, productUrl: "https://eu.renogy.com/collections/new-releases", technicalSpecs: { Environment: "Marine", Focus: "DC distribution", Requirement: "Marine-rated design", "Use case": "Boat systems" }, tags: ["marine", "dc", "battery"], featured: true, recommendedFor: ["Boat"], compatibilityNotes: "Marine systems require corrosion protection, compliant overcurrent protection and vessel-specific review." }),
];
export function productsForCategory(category: string) { return catalog.filter((product) => product.category === category); }
export function productsForRegion(region: MarketplaceRegion) { return catalog.filter((product) => product.merchantRegion === region); }
export function productBySlug(slug: string) { return catalog.find((product) => product.slug === slug); }
