import type { Dictionary, Locale } from "@/lib/i18n/types";

const en: Dictionary = {
  "auth.login": "Login", "auth.register": "Register", "auth.logout": "Logout", "auth.dashboard": "Dashboard",
  "auth.email": "Email address", "auth.password": "Password", "auth.confirmPassword": "Confirm password",
  "auth.signIn": "Sign in", "auth.signUp": "Create account", "auth.forgotPassword": "Forgot password?",
  "auth.noAccount": "Need an account?", "auth.hasAccount": "Already have an account?", "auth.reset": "Reset password",
  "auth.sendReset": "Send reset link", "auth.newPassword": "New password", "auth.updatePassword": "Update password",
  "auth.checkEmail": "Check your email", "auth.verifyMessage": "We sent a verification link to your email address.",
  "auth.resetMessage": "If an account exists for this address, a reset link has been sent.", "auth.backToLogin": "Back to login",
  "auth.role": "Account role", "auth.signInTitle": "Welcome back", "auth.signInDescription": "Sign in securely to continue.",
  "auth.signUpTitle": "Create your account", "auth.signUpDescription": "Start with a verified email address.",
  "auth.resetTitle": "Reset your password", "auth.updateTitle": "Choose a new password", "auth.passwordHint": "At least 8 characters",
  "onboarding.title": "Set up your profile", "onboarding.description": "A few details help us tailor your marketplace experience.",
  "onboarding.role": "Choose your role", "onboarding.country": "Country", "onboarding.language": "Preferred interface language",
  "onboarding.spokenLanguages": "Spoken languages", "onboarding.remote": "Available for remote work", "onboarding.city": "City",
  "onboarding.timezone": "Timezone", "onboarding.currency": "Default currency", "onboarding.continue": "Continue", "onboarding.complete": "Complete setup",
  "onboarding.yes": "Yes", "onboarding.no": "No", "role.client": "Client", "role.expert": "Expert", "role.supplier": "Supplier",
  "role.clientDescription": "Find electrical services and solutions.", "role.expertDescription": "Offer specialist electrical expertise.", "role.supplierDescription": "Supply products and equipment.",
  "dashboard.client.title": "Client Dashboard", "dashboard.expert.title": "Expert Dashboard", "dashboard.supplier.title": "Supplier Dashboard",
  "dashboard.placeholder": "Your marketplace workspace is being prepared.", "dashboard.profile": "Profile", "common.required": "Required",
};

const ru: Dictionary = { ...en,
  "auth.login": "Войти", "auth.register": "Регистрация", "auth.logout": "Выйти", "auth.dashboard": "Панель",
  "auth.email": "Электронная почта", "auth.password": "Пароль", "auth.confirmPassword": "Подтвердите пароль", "auth.signIn": "Войти", "auth.signUp": "Создать аккаунт", "auth.forgotPassword": "Забыли пароль?", "auth.noAccount": "Нет аккаунта?", "auth.hasAccount": "Уже есть аккаунт?", "auth.reset": "Сбросить пароль", "auth.sendReset": "Отправить ссылку", "auth.newPassword": "Новый пароль", "auth.updatePassword": "Обновить пароль", "auth.checkEmail": "Проверьте почту", "auth.verifyMessage": "Мы отправили ссылку для подтверждения на вашу почту.", "auth.resetMessage": "Если аккаунт существует, ссылка для сброса уже отправлена.", "auth.backToLogin": "Назад ко входу", "auth.role": "Роль аккаунта", "auth.signInTitle": "С возвращением", "auth.signInDescription": "Войдите, чтобы продолжить.", "auth.signUpTitle": "Создайте аккаунт", "auth.signUpDescription": "Начните с подтверждённого адреса электронной почты.", "auth.resetTitle": "Сброс пароля", "auth.updateTitle": "Выберите новый пароль", "auth.passwordHint": "Не менее 8 символов",
  "onboarding.title": "Настройте профиль", "onboarding.description": "Несколько деталей помогут настроить маркетплейс.", "onboarding.role": "Выберите роль", "onboarding.country": "Страна", "onboarding.language": "Предпочитаемый язык интерфейса", "onboarding.spokenLanguages": "Разговорные языки", "onboarding.remote": "Доступен для удалённой работы", "onboarding.city": "Город", "onboarding.timezone": "Часовой пояс", "onboarding.currency": "Валюта по умолчанию", "onboarding.continue": "Продолжить", "onboarding.complete": "Завершить настройку", "onboarding.yes": "Да", "onboarding.no": "Нет", "role.client": "Клиент", "role.expert": "Эксперт", "role.supplier": "Поставщик", "role.clientDescription": "Находите электротехнические услуги и решения.", "role.expertDescription": "Предлагайте экспертные электротехнические услуги.", "role.supplierDescription": "Поставляйте товары и оборудование.", "dashboard.client.title": "Панель клиента", "dashboard.expert.title": "Панель эксперта", "dashboard.supplier.title": "Панель поставщика", "dashboard.placeholder": "Ваше рабочее пространство маркетплейса готовится.", "dashboard.profile": "Профиль", "common.required": "Обязательно",
};

const ro: Dictionary = { ...en,
  "auth.login": "Autentificare", "auth.register": "Înregistrare", "auth.logout": "Deconectare", "auth.dashboard": "Panou", "auth.email": "Adresă de e-mail", "auth.password": "Parolă", "auth.confirmPassword": "Confirmă parola", "auth.signIn": "Autentificare", "auth.signUp": "Creează cont", "auth.forgotPassword": "Ai uitat parola?", "auth.noAccount": "Nu ai cont?", "auth.hasAccount": "Ai deja cont?", "auth.reset": "Resetează parola", "auth.sendReset": "Trimite linkul", "auth.newPassword": "Parolă nouă", "auth.updatePassword": "Actualizează parola", "auth.checkEmail": "Verifică e-mailul", "auth.verifyMessage": "Am trimis un link de verificare la adresa ta de e-mail.", "auth.resetMessage": "Dacă există un cont pentru această adresă, un link de resetare a fost trimis.", "auth.backToLogin": "Înapoi la autentificare", "auth.role": "Rolul contului", "auth.signInTitle": "Bun venit înapoi", "auth.signInDescription": "Autentifică-te în siguranță pentru a continua.", "auth.signUpTitle": "Creează-ți contul", "auth.signUpDescription": "Începe cu o adresă de e-mail verificată.", "auth.resetTitle": "Resetează parola", "auth.updateTitle": "Alege o parolă nouă", "auth.passwordHint": "Cel puțin 8 caractere", "onboarding.title": "Configurează-ți profilul", "onboarding.description": "Câteva detalii ne ajută să adaptăm experiența marketplace.", "onboarding.role": "Alege rolul", "onboarding.country": "Țară", "onboarding.language": "Limba preferată a interfeței", "onboarding.spokenLanguages": "Limbi vorbite", "onboarding.remote": "Disponibil pentru lucru la distanță", "onboarding.city": "Oraș", "onboarding.timezone": "Fus orar", "onboarding.currency": "Monedă implicită", "onboarding.continue": "Continuă", "onboarding.complete": "Finalizează configurarea", "onboarding.yes": "Da", "onboarding.no": "Nu", "role.client": "Client", "role.expert": "Expert", "role.supplier": "Furnizor", "role.clientDescription": "Găsește servicii și soluții electrice.", "role.expertDescription": "Oferă expertiză electrică de specialitate.", "role.supplierDescription": "Furnizează produse și echipamente.", "dashboard.client.title": "Panoul clientului", "dashboard.expert.title": "Panoul expertului", "dashboard.supplier.title": "Panoul furnizorului", "dashboard.placeholder": "Spațiul tău de lucru marketplace este în pregătire.", "dashboard.profile": "Profil", "common.required": "Obligatoriu",
};

const dictionaries: Record<Locale, Dictionary> = { en, ru, ro };
export function getDictionary(locale: Locale = "en") { return dictionaries[locale]; }
export function translate(dictionary: Dictionary, key: string) { return dictionary[key] ?? key; }
