import type { Dictionary, Locale } from "@/lib/i18n/types";

const en: Dictionary = {
  "auth.login": "Login", "auth.register": "Register", "auth.logout": "Logout", "auth.dashboard": "Dashboard",
  "auth.email": "Email address", "auth.password": "Password", "auth.confirmPassword": "Confirm password",
  "auth.signIn": "Sign in", "auth.signUp": "Create account", "auth.forgotPassword": "Forgot password?",
  "auth.noAccount": "Need an account?", "auth.hasAccount": "Already have an account?", "auth.reset": "Reset password",
  "auth.sendReset": "Send reset link", "auth.newPassword": "New password", "auth.updatePassword": "Update password",
  "auth.checkEmail": "Check your email", "auth.verifyMessage": "We sent a verification link to your email address.",
  "auth.resetMessage": "If an account exists for this address, a reset link has been sent.", "auth.backToLogin": "Back to login",
  "auth.role": "Account role", "auth.signInTitle": "Welcome back", "auth.signInDescription": "Sign in securely to continue.",
  "auth.signUpTitle": "Create your account", "auth.signUpDescription": "Start with a verified email address.",
  "auth.resetTitle": "Reset your password", "auth.updateTitle": "Choose a new password", "auth.passwordHint": "At least 8 characters",
  "onboarding.title": "Set up your profile", "onboarding.description": "A few details help us tailor your marketplace experience.",
  "onboarding.role": "Choose your role", "onboarding.country": "Country", "onboarding.language": "Preferred interface language",
  "onboarding.spokenLanguages": "Spoken languages", "onboarding.remote": "Available for remote work", "onboarding.city": "City",
  "onboarding.timezone": "Timezone", "onboarding.currency": "Default currency", "onboarding.continue": "Continue", "onboarding.complete": "Complete setup",
  "onboarding.yes": "Yes", "onboarding.no": "No", "role.client": "Client", "role.expert": "Expert", "role.supplier": "Supplier",
  "role.clientDescription": "Find electrical services and solutions.", "role.expertDescription": "Offer specialist electrical expertise.", "role.supplierDescription": "Supply products and equipment.",
  "dashboard.client.title": "Client Dashboard", "dashboard.expert.title": "Expert Dashboard", "dashboard.supplier.title": "Supplier Dashboard",
  "dashboard.placeholder": "Your marketplace workspace is being prepared.", "dashboard.profile": "Profile", "common.required": "Required",
  "onboarding.roleFixed": "Your role was selected when you registered and cannot be changed here.", "onboarding.fullName": "Full name",
  "onboarding.assistance": "Type of assistance needed", "onboarding.companyOptional": "Company (optional)", "onboarding.professionalTitle": "Professional title",
  "onboarding.yearsExperience": "Years of experience", "onboarding.specializations": "Specializations", "onboarding.professionalDescription": "Short professional description",
  "onboarding.contactPerson": "Contact person", "onboarding.companyName": "Company name", "onboarding.productCategories": "Supplied product categories", "onboarding.companyDescription": "Short company description",
  "onboarding.specialization.diagnostics": "Diagnostics", "onboarding.specialization.automation": "Automation", "onboarding.specialization.marine": "Marine", "onboarding.specialization.power": "Power systems",
  "onboarding.category.cables": "Cables", "onboarding.category.protection": "Protection", "onboarding.category.automation": "Automation", "onboarding.category.marine": "Marine equipment",
};

const ru: Dictionary = { ...en,
  "auth.login": "Войти", "auth.register": "Регистрация", "auth.logout": "Выйти", "auth.dashboard": "Панель",
  "auth.email": "Электронная почта", "auth.password": "Пароль", "auth.confirmPassword": "Подтвердите пароль", "auth.signIn": "Войти", "auth.signUp": "Создать аккаунт", "auth.forgotPassword": "Забыли пароль?", "auth.noAccount": "Нет аккаунта?", "auth.hasAccount": "Уже есть аккаунт?", "auth.reset": "Сбросить пароль", "auth.sendReset": "Отправить ссылку", "auth.newPassword": "Новый пароль", "auth.updatePassword": "Обновить пароль", "auth.checkEmail": "Проверьте почту", "auth.verifyMessage": "Мы отправили ссылку для подтверждения на вашу почту.", "auth.resetMessage": "Если аккаунт существует, ссылка для сброса уже отправлена.", "auth.backToLogin": "Назад ко входу", "auth.role": "Роль аккаунта", "auth.signInTitle": "С возвращением", "auth.signInDescription": "Войдите, чтобы продолжить.", "auth.signUpTitle": "Создайте аккаунт", "auth.signUpDescription": "Начните с подтверждённого адреса электронной почты.", "auth.resetTitle": "Сброс пароля", "auth.updateTitle": "Выберите новый пароль", "auth.passwordHint": "Не менее 8 символов",
  "onboarding.title": "Настройте профиль", "onboarding.description": "Несколько деталей помогут настроить маркетплейс.", "onboarding.role": "Выберите роль", "onboarding.country": "Страна", "onboarding.language": "Предпочитаемый язык интерфейса", "onboarding.spokenLanguages": "Разговорные языки", "onboarding.remote": "Доступен для удалённой работы", "onboarding.city": "Город", "onboarding.timezone": "Часовой пояс", "onboarding.currency": "Валюта по умолчанию", "onboarding.continue": "Продолжить", "onboarding.complete": "Завершить настройку", "onboarding.yes": "Да", "onboarding.no": "Нет", "role.client": "Клиент", "role.expert": "Эксперт", "role.supplier": "Поставщик", "role.clientDescription": "Находите электротехнические услуги и решения.", "role.expertDescription": "Предлагайте экспертные электротехнические услуги.", "role.supplierDescription": "Поставляйте товары и оборудование.", "dashboard.client.title": "Панель клиента", "dashboard.expert.title": "Панель эксперта", "dashboard.supplier.title": "Панель поставщика", "dashboard.placeholder": "Ваше рабочее пространство маркетплейса готовится.", "dashboard.profile": "Профиль", "common.required": "Обязательно",
};

const ro: Dictionary = { ...en,
  "auth.login": "Autentificare", "auth.register": "Înregistrare", "auth.logout": "Deconectare", "auth.dashboard": "Panou", "auth.email": "Adresă de e-mail", "auth.password": "Parolă", "auth.confirmPassword": "Confirmă parola", "auth.signIn": "Autentificare", "auth.signUp": "Creează cont", "auth.forgotPassword": "Ai uitat parola?", "auth.noAccount": "Nu ai cont?", "auth.hasAccount": "Ai deja cont?", "auth.reset": "Resetează parola", "auth.sendReset": "Trimite linkul", "auth.newPassword": "Parolă nouă", "auth.updatePassword": "Actualizează parola", "auth.checkEmail": "Verifică e-mailul", "auth.verifyMessage": "Am trimis un link de verificare la adresa ta de e-mail.", "auth.resetMessage": "Dacă există un cont pentru această adresă, un link de resetare a fost trimis.", "auth.backToLogin": "Înapoi la autentificare", "auth.role": "Rolul contului", "auth.signInTitle": "Bun venit înapoi", "auth.signInDescription": "Autentifică-te în siguranță pentru a continua.", "auth.signUpTitle": "Creează-ți contul", "auth.signUpDescription": "Începe cu o adresă de e-mail verificată.", "auth.resetTitle": "Resetează parola", "auth.updateTitle": "Alege o parolă nouă", "auth.passwordHint": "Cel puțin 8 caractere", "onboarding.title": "Configurează-ți profilul", "onboarding.description": "Câteva detalii ne ajută să adaptăm experiența marketplace.", "onboarding.role": "Alege rolul", "onboarding.country": "Țară", "onboarding.language": "Limba preferată a interfeței", "onboarding.spokenLanguages": "Limbi vorbite", "onboarding.remote": "Disponibil pentru lucru la distanță", "onboarding.city": "Oraș", "onboarding.timezone": "Fus orar", "onboarding.currency": "Monedă implicită", "onboarding.continue": "Continuă", "onboarding.complete": "Finalizează configurarea", "onboarding.yes": "Da", "onboarding.no": "Nu", "role.client": "Client", "role.expert": "Expert", "role.supplier": "Furnizor", "role.clientDescription": "Găsește servicii și soluții electrice.", "role.expertDescription": "Oferă expertiză electrică de specialitate.", "role.supplierDescription": "Furnizează produse și echipamente.", "dashboard.client.title": "Panoul clientului", "dashboard.expert.title": "Panoul expertului", "dashboard.supplier.title": "Panoul furnizorului", "dashboard.placeholder": "Spațiul tău de lucru marketplace este în pregătire.", "dashboard.profile": "Profil", "common.required": "Obligatoriu",
};

Object.assign(en, {
  "address.selectCity":"Select city", "address.selectStreet":"Search street", "address.selectBuilding":"Search building", "address.selectCityFirst":"Select city first", "address.selectStreetFirst":"Select street first", "address.providerUnavailable":"Could not load addresses.", "address.manual":"Enter address manually", "address.searching":"Searching addresses…", "address.noResults":"No matching addresses found.", "address.manualBuilding":"No building matches found. You can enter the house number manually.", "address.retry":"Try again", "address.selected":"Selected address", "address.notVerified":"We could not confirm this house number for the selected street.",
  "backup.hoursUnit":"hours", "backup.assumptions":"Estimate assumes 92% inverter efficiency and 80% usable battery depth of discharge. Final electrical design requires an installer review.", "backup.loads.router":"Wi‑Fi router", "backup.loads.fridge":"Fridge", "backup.loads.lighting":"Lighting", "backup.loads.tv":"TV", "backup.loads.laptop":"Laptop / PC", "backup.loads.boiler":"Gas boiler", "backup.loads.pump":"Water pump",
  "marketplace.eyebrow": "ENERGY MARKETPLACE", "marketplace.title": "Equipment choices with energy context.", "marketplace.description": "An energy equipment catalogue designed around backup duration, loads and installation readiness — not a generic service board.", "marketplace.feedUnavailable": "Product feeds are not connected. Demo stock is intentionally not presented as available inventory.", "marketplace.sizeSystem": "Size your system", "marketplace.categories.homeBatteries": "Home Batteries", "marketplace.categories.portableStations": "Portable Power Stations", "marketplace.categories.inverters": "Inverters", "marketplace.categories.solarPanels": "Solar Panels", "marketplace.categories.hybridInverters": "Hybrid Inverters", "marketplace.categories.ups": "UPS Systems", "marketplace.categories.generators": "Generators", "marketplace.categories.ats": "Automatic Transfer Systems", "marketplace.categories.meters": "Energy Meters", "marketplace.categories.smartDevices": "Smart Energy Devices", "marketplace.categories.evChargers": "EV Chargers", "marketplace.categories.cables": "Cables & Protection",
  "experts.back": "Back to experts", "experts.specialties": "Specialties",
  "experts.aria.directory": "Expert directory", "experts.eyebrow": "EXPERT PROFILES", "experts.title": "Verified electrical experts, on demand", "experts.subtitle": "Find a specialist for residential, industrial, marine, and offshore electrical systems.", "experts.searchLabel": "Search experts by specialty", "experts.searchPlaceholder": "Search by specialty: EV charger, PLC, VFD…", "experts.features.verification": "Verification evidence displayed", "experts.features.specialties": "Specialist tracks by electrical vertical", "experts.features.response": "Response expectations are visible", "experts.filters.all": "All experts", "experts.filters.residential": "Residential", "experts.filters.industrial": "Industrial", "experts.filters.marine": "Marine & Offshore", "experts.badges.verified": "Verified", "experts.badges.verifiedTrack": "Verified track", "experts.badges.priorityTrack": "Priority track", "experts.responseTime": "Response time", "experts.availability": "Availability", "experts.available": "Available", "experts.viewProfile": "View profile", "experts.requestHelp": "Request help", "experts.empty.title": "No experts found", "experts.empty.description": "Try changing your search or category.", "experts.empty.clear": "Clear filters", "experts.metadataTitle": "Experts", "experts.metadataDescription": "Find verified experts for residential, industrial, marine, and offshore electrical systems.", "experts.cards.residential.title": "Residential Diagnostics Specialist", "experts.cards.residential.description": "Support for residential electrical diagnostics, distribution boards, circuits, EV chargers, generators, and intermittent faults.", "experts.cards.residential.tags": "Panels · circuits · EV chargers", "experts.cards.residential.response": "Same-day pilot response", "experts.cards.industrial.title": "Industrial Controls and Drives Engineer", "experts.cards.industrial.description": "Specialist support for PLC, VFD, motor systems, MCC panels, sensors, relays, and industrial fault isolation.", "experts.cards.industrial.tags": "PLC · VFD · motors · MCC", "experts.cards.industrial.response": "Priority scheduling", "experts.cards.marine.title": "Marine & Offshore Electro-Technical Expert", "experts.cards.marine.description": "Support for DP, PMS, generators, switchboards, thrusters, automation, alarm systems, and vessel diagnostics.", "experts.cards.marine.tags": "DP · PMS · generators · alarms", "experts.cards.marine.response": "Priority support path",
  "methodology.eyebrow": "Methodology", "methodology.title": "How resilience information is presented.", "methodology.powerStability": "Power Stability Score is an estimate derived from available infrastructure, generation, outage and grid data. It is not a promise of uninterrupted supply.", "methodology.plantGridStatus": "Plant status concerns an individual facility; grid status concerns a regional system. Neither should be inferred from missing information.", "methodology.dataConfidence": "Data confidence expresses source reliability and coverage. Data freshness expresses when information was last confirmed. Not all countries publish real-time information.", "methodology.nearbyGeneration": "Nearby generation does not guarantee local electricity because transmission, distribution, demand, maintenance and grid constraints matter. This service must not be the sole basis for emergency, safety, relocation or investment decisions.", "methodology.disclaimerTitle": "Data disclaimer", "methodology.disclaimerText": "The information provided by Electro-AI is for general informational purposes only. It does not guarantee the accuracy, completeness, real-time availability or continued operation of any power facility or regional grid. Do not use it as the sole basis for emergency, safety, relocation, financial or investment decisions.", "methodology.metadataDescription": "How Electro-AI presents energy resilience information and its limitations.",
  "footer.platform": "Platform", "footer.marketplace": "Marketplace", "footer.company": "Company", "footer.ai": "AI Assistant", "footer.diagnostics": "Diagnostics", "footer.documents": "Documents AI", "footer.experts": "Experts", "footer.knowledge": "Knowledge Base", "footer.contact": "Contact", "footer.about": "About", "footer.privacy": "Privacy Policy", "footer.terms": "Terms",
  "header.tagline": "Diagnostics · Calculators · Experts · Protected marketplace", "header.openMenu": "Open navigation menu", "header.closeMenu": "Close navigation menu", "footer.title": "Built for electrical trust, not generic service noise.", "footer.description": "AI diagnostics, deterministic calculators, expert verification, protected electrical transactions, and premium marine and industrial workflows.", "footer.market": "Primary commercial focus", "footer.international": "International technical operations ready.", "footer.engineering": "Electrical engineering only.", "footer.payments": "Payments should be handled by marketplace providers such as Stripe Connect.",
  "nav.home": "Home", "nav.energy": "Ukraine Energy Live", "nav.myHome": "My Home", "nav.energyAi": "Energy AI", "nav.marketplace": "Energy Marketplace", "nav.map": "Energy Map", "nav.business": "For Business", "nav.backup": "Backup Calculator", "nav.installers": "Find Installer", "nav.buildings": "Buildings", "nav.professionals": "Professionals", "nav.calculators": "Calculators", "nav.more": "More", "nav.pro": "PRO",
  "home.eyebrow": "ENERGY RESILIENCE FOR UKRAINE", "home.title": "Know when power changes. Know how long your home can last.", "home.description": "Live energy information, outage monitoring, backup power calculations, equipment and trusted installers — in one platform.", "home.checkAddress": "Check My Address", "home.calculate": "Calculate Backup Power", "home.energyStatus": "Ukraine Energy Status", "home.sourceUnavailable": "Data source unavailable", "home.addressTitle": "Check your electricity status", "home.addressDescription": "Start with your address. We never replace missing operator data with a made-up schedule.", "home.city": "City", "home.street": "Street", "home.building": "Building number", "home.apartment": "Apartment (optional)", "home.statusUnknown": "Status unknown — no verified distribution-operator address feed is connected yet.",
  "backup.eyebrow": "Backup Calculator", "backup.title": "Plan your essential power.", "backup.description": "Choose household loads and a desired outage duration for a preliminary, technically transparent battery and inverter estimate.", "backup.what": "What do you want to keep running?", "backup.hours": "How long should it work?", "backup.load": "Estimated continuous load", "backup.energy": "Required energy", "backup.battery": "Suggested usable battery", "backup.inverter": "Recommended inverter", "backup.findEquipment": "Find Equipment", "backup.findInstaller": "Find Installer", "backup.askAi": "Ask Energy AI", "common.open": "Open", "common.notAvailable": "Not available", "common.unknown": "Unknown", "language.english": "English", "language.ukrainian": "Українська", "language.label": "Interface language",
});
const uk: Dictionary = { ...en,
  "auth.login": "Увійти", "auth.register": "Реєстрація", "auth.logout": "Вийти", "auth.dashboard": "Кабінет",
  "nav.home": "Головна", "nav.energy": "Енергосистема України", "nav.myHome": "Мій дім", "nav.energyAi": "Energy AI", "nav.marketplace": "Енергетичний маркетплейс", "nav.map": "Енергетична карта", "nav.business": "Для бізнесу", "nav.backup": "Калькулятор резервного живлення", "nav.installers": "Знайти монтажника", "nav.buildings": "Будинки", "nav.professionals": "Фахівцям", "nav.calculators": "Калькулятори", "nav.more": "Ще", "nav.pro": "PRO",
  "home.eyebrow": "ЕНЕРГЕТИЧНА СТІЙКІСТЬ УКРАЇНИ", "home.title": "Знайте, що відбувається з електропостачанням. Знайте, скільки ваш дім зможе працювати автономно.", "home.description": "Актуальні дані про енергосистему, моніторинг відключень, розрахунок резервного живлення, обладнання та перевірені монтажники — на одній платформі.", "home.checkAddress": "Перевірити мою адресу", "home.calculate": "Розрахувати резервне живлення", "home.energyStatus": "Стан енергосистеми України", "home.sourceUnavailable": "Джерело даних недоступне", "home.addressTitle": "Перевірте стан електропостачання", "home.addressDescription": "Почніть з адреси. Ми не замінюємо відсутні дані оператора вигаданим графіком.", "home.city": "Місто", "home.street": "Вулиця", "home.building": "Номер будинку", "home.apartment": "Квартира (необов’язково)", "home.statusUnknown": "Статус невідомий — перевірене джерело оператора системи розподілу для адреси ще не підключено.",
  "backup.eyebrow": "Калькулятор резервного живлення", "backup.title": "Сплануйте живлення для найважливішого.", "backup.description": "Оберіть побутові прилади та тривалість відключення для попереднього, технічно прозорого розрахунку акумулятора й інвертора.", "backup.what": "Що має продовжувати працювати під час відключення?", "backup.hours": "Скільки часу система повинна працювати автономно?", "backup.load": "Розрахункове постійне навантаження", "backup.energy": "Необхідний запас енергії", "backup.battery": "Рекомендований акумулятор", "backup.inverter": "Рекомендований інвертор", "backup.findEquipment": "Знайти обладнання", "backup.findInstaller": "Знайти монтажника", "backup.askAi": "Запитати Energy AI",
  "common.open": "Відкрити", "common.notAvailable": "Немає даних", "common.unknown": "Немає даних", "common.more": "Ще", "language.english": "English", "language.ukrainian": "Українська", "language.label": "Мова інтерфейсу",
};
Object.assign(en, {
  "energy.eyebrow": "Ukraine Energy", "energy.title": "Ukraine Energy System", "energy.description": "Live and historical information about electricity supply, generation, cross-border flows, market prices, gas reserves and regional outages.", "energy.status": "Data status", "energy.demo": "Demo data", "energy.updated": "Last local fixture update", "energy.refresh": "Refresh", "energy.refreshing": "Refreshing…", "energy.share": "Share", "energy.download": "Download data", "energy.methodology": "Methodology", "energy.range.label": "Global date range", "energy.range.today": "Today", "energy.range.week": "7 days", "energy.range.month": "30 days", "energy.range.quarter": "3 months", "energy.range.year": "1 year", "energy.range.since2022": "Since 2022", "energy.source": "Source",
  "energy.kpi.system": "Power system status", "energy.kpi.system.detail": "No official operational feed", "energy.kpi.system.source": "System operator feed not connected", "energy.kpi.flow": "Net import / export", "energy.kpi.flow.detail": "Commercial flow only", "energy.kpi.flow.source": "Demo fixture", "energy.kpi.generation": "Available generation", "energy.kpi.generation.detail": "No verified assessment", "energy.kpi.generation.source": "Demo fixture", "energy.kpi.outages": "Scheduled-outage regions", "energy.kpi.outages.detail": "No current DSO feed", "energy.kpi.outages.source": "Demo fixture", "energy.kpi.gas": "Gas storage", "energy.kpi.gas.detail": "Technical gas excluded when supplied", "energy.kpi.gas.source": "AGSI adapter pending", "energy.kpi.price": "Day-ahead price", "energy.kpi.price.detail": "No market feed", "energy.kpi.price.source": "OREE adapter pending", "energy.kpi.sources": "Data sources online", "energy.kpi.sources.detail": "Demo-mode sources", "energy.kpi.sources.source": "Source registry", "energy.kpi.sync": "Last synchronization", "energy.kpi.sync.detail": "Europe/Kyiv", "energy.kpi.sync.source": "Local fixture",
  "energy.trade.title": "Cross-border electricity trade", "energy.trade.source": "ENTSO-E adapter pending · commercial flows only", "energy.trade.description": "Selected period:", "energy.capacity.title": "Generation capacity status", "energy.capacity.source": "Local demo fixture · unconfirmed", "energy.capacity.operating": "Operating", "energy.capacity.damaged": "Damaged", "energy.capacity.offline": "Temporarily offline", "energy.capacity.description": "No capacity assessment is shown until a dated, attributable source is connected.", "energy.outlook.title": "Regional outage outlook", "energy.outlook.source": "DSO adapters pending · demo fixture", "energy.outlook.note": "Historical outage surveys are never current schedules.", "energy.oblast": "oblast", "energy.address.title": "Address outage check", "energy.address.source": "No DSO address feed connected", "energy.address.oblast": "Oblast", "energy.address.choose": "Choose oblast", "energy.address.city": "City or settlement", "energy.address.street": "Street and building", "energy.address.check": "Check schedule", "energy.address.result": "Not available. A verified distribution-system-operator feed is required before address-level schedules can be shown.", "energy.map.title": "Ukraine public facility map", "energy.map.description": "The map opens directly on Ukraine and uses only public facility records already available in the platform.", "energy.map.open": "Open Ukraine map", "energy.gas.title": "Gas storage reserves", "energy.gas.source": "AGSI adapter pending", "energy.gas.description": "Current volume, fill level, injection and withdrawal are not available in the local fixture.", "energy.market.title": "Day-ahead electricity market", "energy.market.source": "OREE + NBU adapters pending", "energy.market.description": "No current price is displayed.", "energy.flow.direction": "Direction", "energy.flow.value": "Commercial flow", "energy.flow.status": "Status", "energy.disclaimer": "This original Electro-AI dashboard is informed by public methodology. See the", "energy.reference": "public reference methodology",
});
Object.assign(uk, {
  "address.selectCity":"Оберіть місто", "address.selectStreet":"Почніть вводити назву вулиці", "address.selectBuilding":"Оберіть номер будинку", "address.selectCityFirst":"Спочатку оберіть місто", "address.selectStreetFirst":"Спочатку оберіть вулицю", "address.providerUnavailable":"Не вдалося завантажити адреси.", "address.manual":"Ввести адресу вручну", "address.searching":"Шукаємо адресу…", "address.noResults":"Відповідних адрес не знайдено.", "address.manualBuilding":"Номер будинку не знайдено. Його можна ввести вручну.", "address.retry":"Спробувати ще раз", "address.selected":"Обрана адреса", "address.notVerified":"Не вдалося підтвердити цей номер будинку для обраної вулиці.",
  "backup.hoursUnit":"годин", "backup.assumptions":"Розрахунок враховує ефективність інвертора 92% і корисну глибину розряду акумулятора 80%. Остаточний електротехнічний проєкт має перевірити монтажник.", "backup.loads.router":"Wi‑Fi роутер", "backup.loads.fridge":"Холодильник", "backup.loads.lighting":"Освітлення", "backup.loads.tv":"Телевізор", "backup.loads.laptop":"Ноутбук / ПК", "backup.loads.boiler":"Газовий котел", "backup.loads.pump":"Водяний насос",
  "marketplace.eyebrow": "ЕНЕРГЕТИЧНИЙ МАРКЕТПЛЕЙС", "marketplace.title": "Обладнання з урахуванням реальних енергетичних потреб", "marketplace.description": "Каталог енергетичного обладнання, підібраного з урахуванням тривалості резервної роботи, навантаження та готовності до монтажу.", "marketplace.feedUnavailable": "Дані про товари ще не підключені. Демо-товари навмисно не показуються як доступні до покупки.", "marketplace.sizeSystem": "Розрахувати систему", "marketplace.categories.homeBatteries": "Домашні акумулятори", "marketplace.categories.portableStations": "Портативні зарядні станції", "marketplace.categories.inverters": "Інвертори", "marketplace.categories.solarPanels": "Сонячні панелі", "marketplace.categories.hybridInverters": "Гібридні інвертори", "marketplace.categories.ups": "Системи безперебійного живлення", "marketplace.categories.generators": "Генератори", "marketplace.categories.ats": "Системи автоматичного введення резерву", "marketplace.categories.meters": "Лічильники енергії", "marketplace.categories.smartDevices": "Розумні енергетичні пристрої", "marketplace.categories.evChargers": "Зарядні пристрої для EV", "marketplace.categories.cables": "Кабелі та захист",
  "experts.back": "Повернутися до фахівців", "experts.specialties": "Спеціалізації",
  "experts.aria.directory": "Каталог фахівців", "experts.eyebrow": "ПРОФІЛІ ФАХІВЦІВ", "experts.title": "Перевірені фахівці з електротехніки", "experts.subtitle": "Знайдіть фахівця для домашніх, промислових, морських та офшорних електротехнічних систем.", "experts.searchLabel": "Пошук фахівців за спеціалізацією", "experts.searchPlaceholder": "Пошук за спеціалізацією: EV charger, PLC, VFD…", "experts.features.verification": "Показуємо підтвердження кваліфікації", "experts.features.specialties": "Фахівці за напрямами електротехніки", "experts.features.response": "Видно орієнтовний час відповіді", "experts.filters.all": "Усі фахівці", "experts.filters.residential": "Побутові системи", "experts.filters.industrial": "Промисловість", "experts.filters.marine": "Морські та офшорні системи", "experts.badges.verified": "Перевірено", "experts.badges.verifiedTrack": "Перевірений профіль", "experts.badges.priorityTrack": "Пріоритетний профіль", "experts.responseTime": "Час відповіді", "experts.availability": "Доступність", "experts.available": "Доступний", "experts.viewProfile": "Переглянути профіль", "experts.requestHelp": "Запросити допомогу", "experts.empty.title": "Фахівців не знайдено", "experts.empty.description": "Спробуйте змінити параметри пошуку або категорію.", "experts.empty.clear": "Очистити фільтри", "experts.metadataTitle": "Фахівці", "experts.metadataDescription": "Знайдіть перевірених фахівців з побутових, промислових, морських та офшорних електротехнічних систем.", "experts.cards.residential.title": "Фахівець з діагностики побутових електросистем", "experts.cards.residential.description": "Професійна підтримка з діагностики побутових електросистем, електрощитів, групових кіл, зарядних станцій для електромобілів, генераторів та складних періодичних несправностей.", "experts.cards.residential.tags": "Щити · кола · EV charger", "experts.cards.residential.response": "Відповідь для пілотних користувачів того ж дня", "experts.cards.industrial.title": "Інженер промислової автоматики та електроприводів", "experts.cards.industrial.description": "Спеціалізація на PLC, VFD, електродвигунах, MCC-панелях, датчиках, реле та пошуку несправностей на промислових об’єктах.", "experts.cards.industrial.tags": "PLC · VFD · двигуни · MCC", "experts.cards.industrial.response": "Пріоритетне планування", "experts.cards.marine.title": "Морський та офшорний електротехнічний фахівець", "experts.cards.marine.description": "Професійна підтримка для DP, PMS, генераторів, головних розподільних щитів, підрулювальних пристроїв, автоматики, систем сигналізації та діагностики суднового обладнання.", "experts.cards.marine.tags": "DP · PMS · генератори · сигналізація", "experts.cards.marine.response": "Пріоритетний канал підтримки",
  "methodology.eyebrow": "Методологія", "methodology.title": "Як Electro-AI відображає інформацію про енергетичну стійкість", "methodology.powerStability": "Індекс стабільності електропостачання — це орієнтовний показник, сформований на основі доступних даних про інфраструктуру, генерацію, відключення та стан електромережі. Він не є гарантією безперервного електропостачання.", "methodology.plantGridStatus": "Статус електростанції стосується окремого енергетичного об’єкта, а статус мережі — регіональної енергосистеми. Відсутність даних не означає, що об’єкт або мережа не працюють.", "methodology.dataConfidence": "Достовірність даних відображає надійність джерела та повноту доступної інформації. Актуальність даних показує, коли інформацію було востаннє підтверджено. Не всі джерела публікують інформацію в режимі реального часу.", "methodology.nearbyGeneration": "Наявність генерації поблизу не гарантує електропостачання конкретного району, оскільки впливають передача, розподіл, споживання, ремонти та обмеження мережі. Не використовуйте сервіс як єдину основу для рішень щодо надзвичайних ситуацій, безпеки, переїзду або інвестицій.", "methodology.disclaimerTitle": "Важлива інформація про дані", "methodology.disclaimerText": "Інформація, яку надає Electro-AI, має загальний інформаційний характер. Electro-AI не гарантує абсолютну точність, повноту, доступність у режимі реального часу або безперервну роботу будь-якого енергетичного об’єкта чи регіональної електромережі. Не використовуйте ці дані як єдину основу для рішень, пов’язаних із надзвичайними ситуаціями, безпекою, переїздом, фінансами або інвестиціями.", "methodology.metadataDescription": "Як Electro-AI відображає дані про енергетичну стійкість та їхні обмеження.",
  "footer.platform": "Платформа", "footer.marketplace": "Маркетплейс", "footer.company": "Компанія", "footer.ai": "AI-помічник", "footer.diagnostics": "Діагностика", "footer.documents": "Документи AI", "footer.experts": "Фахівці", "footer.knowledge": "База знань", "footer.contact": "Контакти", "footer.about": "Про нас", "footer.privacy": "Політика конфіденційності", "footer.terms": "Умови користування",
  "header.tagline": "Діагностика · Калькулятори · Фахівці · Захищений маркетплейс", "header.openMenu": "Відкрити меню навігації", "header.closeMenu": "Закрити меню навігації", "footer.title": "Створено для електротехнічної надійності, а не для шаблонних сервісів.", "footer.description": "AI-діагностика, детерміновані калькулятори, перевірка фахівців, захищені електротехнічні угоди та професійні морські й промислові сценарії.", "footer.market": "Основний комерційний ринок", "footer.international": "Готово до міжнародних технічних операцій.", "footer.engineering": "Лише електротехнічні послуги.", "footer.payments": "Платежі мають оброблятися провайдерами маркетплейсу, наприклад Stripe Connect.",
  "energy.eyebrow": "Енергосистема України", "energy.title": "Енергосистема України", "energy.description": "Актуальна та історична інформація про електропостачання, генерацію, міждержавні перетоки, ринкові ціни, запаси газу та регіональні відключення.", "energy.status": "Статус даних", "energy.demo": "Демонстраційні дані", "energy.updated": "Останнє оновлення локального набору", "energy.refresh": "Оновити", "energy.refreshing": "Оновлення…", "energy.share": "Поділитися", "energy.download": "Завантажити дані", "energy.methodology": "Методологія", "energy.range.label": "Період даних", "energy.range.today": "Сьогодні", "energy.range.week": "7 днів", "energy.range.month": "30 днів", "energy.range.quarter": "3 місяці", "energy.range.year": "1 рік", "energy.range.since2022": "З 2022 року", "energy.source": "Джерело",
  "energy.kpi.system": "Стан енергосистеми", "energy.kpi.system.detail": "Офіційне оперативне джерело не підключено", "energy.kpi.system.source": "Канал системного оператора не підключено", "energy.kpi.flow": "Чистий імпорт / експорт", "energy.kpi.flow.detail": "Лише комерційний перетік", "energy.kpi.flow.source": "Демонстраційний набір", "energy.kpi.generation": "Доступна генерація", "energy.kpi.generation.detail": "Немає перевіреної оцінки", "energy.kpi.generation.source": "Демонстраційний набір", "energy.kpi.outages": "Регіони з плановими відключеннями", "energy.kpi.outages.detail": "Немає поточного каналу ОСР", "energy.kpi.outages.source": "Демонстраційний набір", "energy.kpi.gas": "Запаси газу", "energy.kpi.gas.detail": "Технічний газ виключається, якщо надається", "energy.kpi.gas.source": "Адаптер AGSI очікує підключення", "energy.kpi.price": "Ціна РДН", "energy.kpi.price.detail": "Ринкове джерело не підключено", "energy.kpi.price.source": "Адаптер OREE очікує підключення", "energy.kpi.sources": "Джерела даних онлайн", "energy.kpi.sources.detail": "Джерела у демо-режимі", "energy.kpi.sources.source": "Реєстр джерел", "energy.kpi.sync": "Остання синхронізація", "energy.kpi.sync.detail": "Europe/Kyiv", "energy.kpi.sync.source": "Локальний набір",
  "energy.trade.title": "Міждержавна торгівля електроенергією", "energy.trade.source": "Адаптер ENTSO-E очікує підключення · лише комерційні перетоки", "energy.trade.description": "Обраний період:", "energy.capacity.title": "Стан генеруючих потужностей", "energy.capacity.source": "Локальний демонстраційний набір · не підтверджено", "energy.capacity.operating": "В роботі", "energy.capacity.damaged": "Пошкоджено", "energy.capacity.offline": "Тимчасово недоступно", "energy.capacity.description": "Оцінка потужностей не показується, доки не буде підключено датоване та атрибутоване джерело.", "energy.outlook.title": "Огляд регіональних відключень", "energy.outlook.source": "Адаптери ОСР очікують підключення · демонстраційний набір", "energy.outlook.note": "Історичні огляди відключень не подаються як поточні графіки.", "energy.oblast": "область", "energy.address.title": "Перевірка відключень за адресою", "energy.address.source": "Канал ОСР для адрес не підключено", "energy.address.oblast": "Область", "energy.address.choose": "Оберіть область", "energy.address.city": "Місто або населений пункт", "energy.address.street": "Вулиця та номер будинку", "energy.address.check": "Перевірити графік", "energy.address.result": "Даних немає. Для показу графіків за адресою потрібне перевірене джерело оператора системи розподілу.", "energy.map.title": "Публічна карта енергетичних об’єктів України", "energy.map.description": "Карта відкривається одразу на території України та використовує лише публічні записи об’єктів на платформі.", "energy.map.open": "Відкрити карту України", "energy.gas.title": "Запаси газу в сховищах", "energy.gas.source": "Адаптер AGSI очікує підключення", "energy.gas.description": "Поточний обсяг, рівень заповнення, закачування та відбір недоступні в локальному наборі.", "energy.market.title": "Ринок електроенергії на добу наперед", "energy.market.source": "Адаптери OREE + НБУ очікують підключення", "energy.market.description": "Поточна ціна не відображається.", "energy.flow.direction": "Напрямок", "energy.flow.value": "Комерційний перетік", "energy.flow.status": "Статус", "energy.disclaimer": "Ця оригінальна панель Electro-AI спирається на публічну методологію. Див.", "energy.reference": "публічну методологію-джерело",
});
void ru;
void ro;
const dictionaries: Record<Locale, Dictionary> = { en, uk };
export function getDictionary(locale: Locale = "en") { return dictionaries[locale]; }
export function translate(dictionary: Dictionary, key: string) { return dictionary[key] ?? key; }
