"use client";
import { useEffect, useRef } from "react";
import type { MutableRefObject } from "react";
import type { Map as MapLibreMap } from "maplibre-gl";
import { powerPlantsToGeoJson } from "@/lib/map/power-plants-to-geojson";
import type { PowerPlant } from "@/types/power";
const sourceId = "power-plants"; const selectedSourceId = "selected-plant"; const demoMapStyleUrl = "https://tiles.openfreemap.org/styles/liberty";
export function MapLibreCanvas({ mapRef, plants, selectedPlant, onSelect, onReady, onError }: { mapRef: MutableRefObject<MapLibreMap | null>; plants: PowerPlant[]; selectedPlant: PowerPlant | null; onSelect: (plant: PowerPlant) => void; onReady: (map: MapLibreMap) => void; onError: () => void }) {
 const containerRef = useRef<HTMLDivElement>(null); const plantsRef = useRef(plants); useEffect(() => { plantsRef.current = plants; }, [plants]);
 useEffect(() => { if (!containerRef.current || mapRef.current) return; let map: MapLibreMap | null = null; void import("maplibre-gl").then((maplibregl) => { if (!containerRef.current) return; const instance = new maplibregl.Map({ container: containerRef.current, style: process.env.NEXT_PUBLIC_MAP_STYLE_URL ?? demoMapStyleUrl, center: [16, 30], zoom: 1.35 }); map = instance; mapRef.current = instance; instance.addControl(new maplibregl.NavigationControl(), "bottom-right"); instance.addControl(new maplibregl.ScaleControl(), "bottom-left"); instance.on("error", onError); instance.on("load", () => { instance.addSource(sourceId, { type: "geojson", data: powerPlantsToGeoJson(plantsRef.current), cluster: true, clusterRadius: 48 }); instance.addLayer({ id: "clusters", type: "circle", source: sourceId, filter: ["has", "point_count"], paint: { "circle-color": "#16b8b1", "circle-radius": ["step", ["get", "point_count"], 18, 10, 24, 30, 30] } }); instance.addLayer({ id: "cluster-count", type: "symbol", source: sourceId, filter: ["has", "point_count"], layout: { "text-field": ["get", "point_count_abbreviated"], "text-size": 12 }, paint: { "text-color": "#ffffff" } }); instance.addLayer({ id: "plants", type: "circle", source: sourceId, filter: ["!", ["has", "point_count"]], paint: { "circle-color": "#2da87b", "circle-radius": ["interpolate", ["linear"], ["get", "capacity"], 0, 6, 1000, 10, 10000, 15], "circle-stroke-color": "#ffffff", "circle-stroke-width": 2 } }); instance.addSource(selectedSourceId, { type: "geojson", data: { type: "FeatureCollection", features: [] } }); instance.addLayer({ id: "selected-plant", type: "circle", source: selectedSourceId, paint: { "circle-color": "#092b35", "circle-radius": 15, "circle-stroke-color": "#ffffff", "circle-stroke-width": 3 } }); instance.addLayer({ id: "selected-plant-label", type: "symbol", source: selectedSourceId, layout: { "text-field": ["get", "name"], "text-offset": [0, 1.8], "text-size": 13 }, paint: { "text-color": "#092b35", "text-halo-color": "#ffffff", "text-halo-width": 2 } }); instance.on("click", "plants", (event) => { const id = event.features?.[0]?.properties?.id; const plant = plantsRef.current.find((item) => item.id === id); if (plant) onSelect(plant); }); instance.on("click", "clusters", (event) => { const feature = event.features?.[0]; const clusterId = feature?.properties?.cluster_id; const coordinates = feature?.geometry.type === "Point" ? feature.geometry.coordinates as [number, number] : null; const source = instance.getSource(sourceId) as import("maplibre-gl").GeoJSONSource | undefined; if (typeof clusterId === "number" && coordinates && source) source.getClusterExpansionZoom(clusterId).then((zoom) => instance.easeTo({ center: coordinates, zoom })); }); onReady(instance); }); }).catch(onError); return () => { map?.remove(); mapRef.current = null; }; }, [mapRef, onError, onReady, onSelect]);
 useEffect(() => { const source = mapRef.current?.getSource(sourceId) as import("maplibre-gl").GeoJSONSource | undefined; source?.setData(powerPlantsToGeoJson(plants)); }, [mapRef, plants]);
 useEffect(() => { const source = mapRef.current?.getSource(selectedSourceId) as import("maplibre-gl").GeoJSONSource | undefined; if (!source) return; source.setData(selectedPlant ? powerPlantsToGeoJson([selectedPlant]) : { type: "FeatureCollection", features: [] }); mapRef.current?.resize(); }, [mapRef, selectedPlant]);
 return <div ref={containerRef} className="h-[min(70vh,700px)] min-h-[420px] overflow-hidden rounded-[1.75rem] border border-white/80 shadow-[0_18px_45px_rgba(10,66,75,0.14)]" aria-label="Interactive world power infrastructure map"/>;
}
