"use client";
import Link from "next/link";
import { useActionState } from "react";
import type { Dictionary } from "@/lib/i18n/types";
import type { ActionState } from "@/app/(auth)/actions";

type Props = { dictionary: Dictionary; action: (state: ActionState, formData: FormData) => Promise<ActionState>; mode: "login" | "register" | "forgot" | "reset" };
export function AuthForm({ dictionary: t, action, mode }: Props) {
  const [state, formAction, pending] = useActionState(action, {});
  const register = mode === "register"; const password = mode === "login" || mode === "register" || mode === "reset";
  const title = mode === "login" ? t["auth.signInTitle"] : mode === "register" ? t["auth.signUpTitle"] : mode === "forgot" ? t["auth.resetTitle"] : t["auth.updateTitle"];
  const submit = mode === "login" ? t["auth.signIn"] : mode === "register" ? t["auth.signUp"] : mode === "forgot" ? t["auth.sendReset"] : t["auth.updatePassword"];
  return <section className="glass-panel mx-auto w-full max-w-md rounded-[2rem] p-6 sm:p-8"><h1 className="font-display text-3xl font-semibold">{title}</h1>{mode === "login" && <p className="mt-2 text-sm text-white/68">{t["auth.signInDescription"]}</p>}{mode === "register" && <p className="mt-2 text-sm text-white/68">{t["auth.signUpDescription"]}</p>}<form action={formAction} className="mt-7 space-y-4">{mode !== "reset" && <label className="block text-sm font-medium">{t["auth.email"]}<input name="email" type="email" autoComplete="email" required className="mt-2 w-full rounded-xl border border-white/20 bg-slate-950/30 px-3 py-3 text-white" /></label>}{password && <label className="block text-sm font-medium">{mode === "reset" ? t["auth.newPassword"] : t["auth.password"]}<input name="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={8} required className="mt-2 w-full rounded-xl border border-white/20 bg-slate-950/30 px-3 py-3 text-white" /></label>}{(register || mode === "reset") && <label className="block text-sm font-medium">{t["auth.confirmPassword"]}<input name="confirmation" type="password" autoComplete="new-password" minLength={8} required className="mt-2 w-full rounded-xl border border-white/20 bg-slate-950/30 px-3 py-3 text-white" /></label>}{register && <label className="block text-sm font-medium">{t["auth.role"]}<select name="role" defaultValue="client" className="mt-2 w-full rounded-xl border border-white/20 bg-slate-950/50 px-3 py-3 text-white"><option value="client">{t["role.client"]}</option><option value="expert">{t["role.expert"]}</option><option value="supplier">{t["role.supplier"]}</option></select></label>}{state.error && <p role="alert" className="text-sm text-red-200">{state.error}</p>}{state.message && <p role="status" className="text-sm text-lime-100">{state.message}</p>}<button disabled={pending} className="w-full rounded-xl bg-lime-300 px-4 py-3 font-semibold text-slate-950 disabled:opacity-60">{submit}</button></form>{mode === "login" && <div className="mt-5 flex justify-between text-sm text-white/75"><Link href="/forgot-password">{t["auth.forgotPassword"]}</Link><Link href="/register">{t["auth.register"]}</Link></div>}{mode === "register" && <p className="mt-5 text-sm text-white/75">{t["auth.hasAccount"]} <Link className="text-lime-200" href="/login">{t["auth.login"]}</Link></p>}{(mode === "forgot" || mode === "reset") && <Link className="mt-5 inline-block text-sm text-lime-200" href="/login">{t["auth.backToLogin"]}</Link>}</section>;
}
