"use client";
import Link from "next/link";
import { useActionState } from "react";
import type { Dictionary } from "@/lib/i18n/types";
import type { ActionState } from "@/app/(auth)/actions";

type Props = { dictionary: Dictionary; action: (state: ActionState, formData: FormData) => Promise<ActionState>; mode: "login" | "register" | "forgot" | "reset" };
export function AuthForm({ dictionary: t, action, mode }: Props) {
  const [state, formAction, pending] = useActionState(action, {});
  const register = mode === "register"; const password = mode === "login" || mode === "register" || mode === "reset";
  const title = mode === "login" ? t["auth.signInTitle"] : mode === "register" ? t["auth.signUpTitle"] : mode === "forgot" ? t["auth.resetTitle"] : t["auth.updateTitle"];
  const submit = mode === "login" ? t["auth.signIn"] : mode === "register" ? t["auth.signUp"] : mode === "forgot" ? t["auth.sendReset"] : t["auth.updatePassword"];
  return <section className="glass-panel mx-auto w-full max-w-md rounded-[2rem] p-6 text-slate-900 sm:p-8"><h1 className="font-display text-3xl font-semibold">{title}</h1>{mode === "login" && <p className="mt-2 text-sm text-slate-600">{t["auth.signInDescription"]}</p>}{mode === "register" && <p className="mt-2 text-sm text-slate-600">{t["auth.signUpDescription"]}</p>}<form action={formAction} className="mt-7 space-y-4">{mode !== "reset" && <label className="block text-sm font-medium">{t["auth.email"]}<input name="email" type="email" autoComplete="email" required className="form-control" /></label>}{password && <label className="block text-sm font-medium">{mode === "reset" ? t["auth.newPassword"] : t["auth.password"]}<input name="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={8} required className="form-control" /></label>}{(register || mode === "reset") && <label className="block text-sm font-medium">{t["auth.confirmPassword"]}<input name="confirmation" type="password" autoComplete="new-password" minLength={8} required className="form-control" /></label>}{register && <label className="block text-sm font-medium">{t["auth.role"]}<select name="role" defaultValue="client" className="form-control"><option value="client">{t["role.client"]}</option><option value="expert">{t["role.expert"]}</option></select></label>}{state.error && <p role="alert" className="text-sm text-rose-700">{state.error}</p>}{state.message && <p role="status" className="text-sm text-teal-800">{state.message}</p>}<button disabled={pending} className="button-primary w-full disabled:cursor-not-allowed disabled:opacity-60">{submit}</button></form>{mode === "login" && <div className="mt-5 flex justify-between text-sm text-slate-600"><Link href="/forgot-password">{t["auth.forgotPassword"]}</Link><Link href="/register">{t["auth.register"]}</Link></div>}{mode === "register" && <p className="mt-5 text-sm text-slate-600">{t["auth.hasAccount"]} <Link className="text-teal-700" href="/login">{t["auth.login"]}</Link></p>}{(mode === "forgot" || mode === "reset") && <Link className="mt-5 inline-block text-sm text-teal-700" href="/login">{t["auth.backToLogin"]}</Link>}</section>;
}
