"use client";
import { useActionState } from "react";
import type { ActionState } from "@/app/(auth)/actions";
import type { Country } from "@/lib/i18n/countries";
import type { Dictionary } from "@/lib/i18n/types";
import type { Profile } from "@/lib/supabase/types";
export function OnboardingForm({ action, countries, dictionary: t, profile, ro }: { action: (state: ActionState, formData: FormData) => Promise<ActionState>; countries: Country[]; dictionary: Dictionary; profile: Profile; ro: boolean }) {
 const [state, formAction, pending] = useActionState(action, {});
 return <section className="content-panel mx-auto w-full max-w-2xl"><h1 className="text-3xl font-semibold">{ro ? "Editează profilul" : "Edit profile"}</h1><p>{ro ? "Datele sunt salvate în profilul privat al contului." : "Details are saved to your private account profile."}</p><form action={formAction} className="mt-6 space-y-4"><label className="block">{t["onboarding.fullName"]}<input name="full_name" required maxLength={200} defaultValue={profile.full_name ?? ""} autoComplete="name" className="form-control"/></label><label className="block">{t["onboarding.country"]}<select name="country_code" required defaultValue={profile.country_code ?? "RO"} className="form-control">{countries.map(c => <option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label className="block">{t["onboarding.language"]}<select name="preferred_language" defaultValue={profile.preferred_language === "en" ? "en" : "ro"} className="form-control"><option value="ro">Română</option><option value="en">English</option></select></label>
 {profile.role === "client" ? <><label className="block">{ro ? "Cerințe energetice / proiect" : "Energy requirements / project"}<textarea required name="assistance_type" maxLength={4000} defaultValue={profile.assistance_type ?? ""} rows={4} className="form-control"/></label><label className="block">{t["onboarding.companyOptional"]}<input name="company_name" defaultValue={profile.company_name ?? ""} className="form-control"/></label><label className="block">{t["onboarding.companyDescription"]}<textarea name="company_description" defaultValue={profile.company_description ?? ""} className="form-control"/></label></> : <><label className="block">{t["onboarding.professionalTitle"]}<input required name="professional_title" defaultValue={profile.professional_title ?? ""} className="form-control"/></label><label className="block">{t["onboarding.yearsExperience"]}<input required name="years_experience" type="number" min="0" max="80" defaultValue={profile.years_experience ?? 0} className="form-control"/></label><label className="block">{t["onboarding.professionalDescription"]}<textarea required name="professional_description" rows={4} defaultValue={profile.professional_description ?? ""} className="form-control"/></label>{profile.specializations.map(s => <input key={s} type="hidden" name="specializations" value={s}/>)}</>}
 {state.error && <p role="alert">{state.error}</p>}<button disabled={pending} className="button-primary w-full">{pending ? (ro ? "Se salvează…" : "Saving…") : (ro ? "Salvează profilul" : "Save profile")}</button></form></section>;
}
