import type { DataConfidence, GridStatus, PowerPlantStatus } from "@/types/power";
const plantLabels: Record<PowerPlantStatus, string> = { operating: "Operating", partial: "Partially operating", planned_outage: "Planned outage", unplanned_outage: "Unplanned outage", construction: "Under construction", decommissioned: "Decommissioned", unknown: "Unknown" };
const gridLabels: Record<GridStatus, string> = { normal: "Normal", strained: "Strained", shortage: "Shortage", rolling_blackouts: "Rolling blackouts", major_outage: "Major outage", unknown: "Unknown" };
const tones: Record<string, string> = { operating: "bg-emerald-100 text-emerald-800", normal: "bg-emerald-100 text-emerald-800", partial: "bg-amber-100 text-amber-800", planned_outage: "bg-amber-100 text-amber-800", strained: "bg-amber-100 text-amber-800", construction: "bg-sky-100 text-sky-800", unplanned_outage: "bg-rose-100 text-rose-800", shortage: "bg-rose-100 text-rose-800", rolling_blackouts: "bg-rose-100 text-rose-800", major_outage: "bg-rose-100 text-rose-800", decommissioned: "bg-slate-100 text-slate-700", unknown: "bg-slate-100 text-slate-700" };
export function PowerPlantStatusBadge({ status }: { status: PowerPlantStatus }) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${tones[status]}`}><span aria-hidden>●</span>{plantLabels[status]}</span>; }
export function GridStatusBadge({ status }: { status: GridStatus }) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${tones[status]}`}><span aria-hidden>●</span>{gridLabels[status]}</span>; }
export function DataConfidenceBadge({ confidence }: { confidence: DataConfidence }) { return <span className="rounded-full bg-cyan-50 px-2.5 py-1 text-xs font-semibold text-cyan-800">{confidence} confidence</span>; }
export function StabilityScore({ score }: { score?: number | null }) { const value = score ?? null; return <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-full border-4 border-teal-300 bg-white/80 text-center text-lg font-bold text-slate-900" aria-label={value == null ? "Stability score not available" : `Power Stability Score ${value} out of 100`}>{value ?? "—"}</div>; }
export function DemoDataBadge() { return <span className="rounded-full border border-cyan-200 bg-cyan-50 px-2.5 py-1 text-xs font-semibold text-cyan-900">Demonstration data</span>; }
