import { notFound } from "next/navigation";
import Link from "next/link";
import { PlatformShell } from "@/components/platform-shell";
import { Breadcrumbs, Intro, LinkGrid, Faq } from "@/components/marketplace/shared";
import { CatalogBrowser } from "@/components/marketplace/catalog-browser";
import { AffiliateDisclosure } from "@/components/marketplace/affiliate-disclosure";
import { categoryByPath, categoryChildren, local } from "@/lib/marketplace/content";
import { catalog } from "@/lib/affiliate/catalog";
import { getRequestLocale, getRequestDictionary } from "@/lib/i18n/request";
import { buildMetadata } from "@/lib/metadata";
import type { CatalogQuery } from "@/lib/marketplace/query";
type Props = { params: Promise<{path:string[]}>; searchParams: Promise<CatalogQuery> };
export async function generateMetadata({params,searchParams}:Props) { const c=categoryByPath((await params).path.join("/")); if(!c)notFound();const locale=await getRequestLocale();const query=await searchParams;return {...buildMetadata({title:local(c.title,locale),description:local(c.summary,locale),path:`/marketplace/${c.path}`}),robots:Object.values(query).some(Boolean)?{index:false,follow:true}:undefined}; }
export default async function CategoryPage({params,searchParams}:Props){const c=categoryByPath((await params).path.join("/"));if(!c)notFound();const locale=await getRequestLocale();const ro=locale==="ro";const t=await getRequestDictionary();const query=await searchParams;const segments=c.path.split("/");const crumbs=[{name:"Marketplace",path:"/marketplace"},...segments.map((_,i)=>{const path=segments.slice(0,i+1).join("/");return {name:local(categoryByPath(path)!.title,locale),path:`/marketplace/${path}`};})];return <PlatformShell><main className="commerce-page"><Breadcrumbs items={crumbs}/><Intro eyebrow="Marketplace · România / EU" title={local(c.title,locale)} description={local(c.summary,locale)}/><LinkGrid locale={locale} items={categoryChildren(c.path).map(n=>({href:`/marketplace/${n.path}`,title:n.title,summary:n.summary}))}/><p className="category-topics">{local(c.topics,locale)}</p><CatalogBrowser products={catalog.filter(p=>p.paths.includes(c.path))} query={query} path={`/marketplace/${c.path}`} facets={c.facets} dictionary={t} ro={ro}/><div className="two-columns"><section className="content-panel"><h2>{ro?"Cum alegi":"How to choose"}</h2><p>{local(c.choose,locale)}</p><Link href={`/learn/${c.guide}`}>{ro?"Citește ghidul complet":"Read the full buying guide"} →</Link></section><section className="content-panel"><h2>{ro?"Verificări tehnice":"Technical considerations"}</h2><p>{local(c.checks,locale)}</p><Link href={c.calculator}>{ro?"Calculează cerințele":"Calculate the requirements"} →</Link></section></div><section className="content-panel"><h2>{ro?"De la categorie la sistem":"From category to system"}</h2><p>{ro?"Continuă cu un scenariu de utilizare și compară componentele în contextul întregului sistem.":"Continue with an application scenario and compare components in the context of the complete system."}</p><div className="action-row"><Link href={`/solutions/${c.solution}`}>{ro?"Soluție recomandată":"Related solution"} →</Link><Link href="/compare">{ro?"Compară echipamente":"Compare equipment"} →</Link><Link href="/marketplace/find-my-solution">{ro?"Găsește soluția":"Find My Solution"} →</Link></div></section><Faq ro={ro} question={ro?`Ce verific înainte de alegerea categoriei ${local(c.title,locale)}?`:`What should I verify before choosing ${local(c.title,locale).toLowerCase()}?`} answer={local(c.checks,locale)}/><AffiliateDisclosure dictionary={t}/></main></PlatformShell>;}
