-- Global Power Resilience Map schema. Legal text and operational-data claims require professional review before launch.
create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade,
  plan_id text not null default 'free' check (plan_id in ('free','premium','professional')),
  status text not null default 'free' check (status in ('free','active','past_due','cancelled')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id)
);
create table if not exists public.power_plants (id uuid primary key default gen_random_uuid(), external_id text unique, name text not null, country_code text not null, latitude double precision not null check (latitude between -90 and 90), longitude double precision not null check (longitude between -180 and 180), source text not null, installed_capacity_mw numeric check (installed_capacity_mw >= 0), is_verified boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.regions (id uuid primary key default gen_random_uuid(), name text not null, country_code text not null, region_type text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.region_power_summaries (id uuid primary key default gen_random_uuid(), region_id uuid not null references public.regions(id) on delete cascade, stability_score integer check (stability_score between 0 and 100), grid_status text not null, confidence text not null, measured_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.plant_status_history (id uuid primary key default gen_random_uuid(), power_plant_id uuid not null references public.power_plants(id) on delete cascade, status text not null, confidence text not null, observed_at timestamptz not null default now());
create table if not exists public.generation_measurements (id uuid primary key default gen_random_uuid(), power_plant_id uuid not null references public.power_plants(id) on delete cascade, generation_mw numeric check (generation_mw >= 0), measured_at timestamptz not null default now());
create table if not exists public.data_sources (id uuid primary key default gen_random_uuid(), name text not null, url text, is_official boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.power_plant_data_sources (power_plant_id uuid references public.power_plants(id) on delete cascade, data_source_id uuid references public.data_sources(id) on delete cascade, primary key(power_plant_id, data_source_id));
create table if not exists public.saved_locations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, location_type text not null check (location_type in ('plant','region')), power_plant_id uuid references public.power_plants(id) on delete cascade, region_id uuid references public.regions(id) on delete cascade, created_at timestamptz not null default now(), check ((power_plant_id is not null) <> (region_id is not null)));
create table if not exists public.alerts (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, location_type text not null check (location_type in ('plant','region')), power_plant_id uuid references public.power_plants(id) on delete cascade, region_id uuid references public.regions(id) on delete cascade, alert_type text not null, threshold integer check (threshold between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists power_plants_country_idx on public.power_plants(country_code); create index if not exists saved_locations_user_idx on public.saved_locations(user_id); create index if not exists alerts_user_idx on public.alerts(user_id);
alter table public.subscriptions enable row level security; alter table public.power_plants enable row level security; alter table public.regions enable row level security; alter table public.region_power_summaries enable row level security; alter table public.saved_locations enable row level security; alter table public.alerts enable row level security;
create policy "verified plants are readable" on public.power_plants for select using (is_verified = true); create policy "regions are readable" on public.regions for select using (true); create policy "summaries are readable" on public.region_power_summaries for select using (true);
create policy "users manage own saved locations" on public.saved_locations for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "users manage own alerts" on public.alerts for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "users read own subscription" on public.subscriptions for select using (auth.uid() = user_id);
