import Link from "next/link";
import { PlatformShell } from "@/components/platform-shell";
import { Intro } from "@/components/marketplace/shared";
import { getRequestLocale } from "@/lib/i18n/request";
import { buildMetadata } from "@/lib/metadata";
const questions=[
 ["Buying","Cumpărare","Can I order here?","Pot comanda aici?","No. We help you calculate and compare; the external supplier handles the order, payment and delivery.","Nu. Te ajutăm să calculezi și să compari; furnizorul extern gestionează comanda, plata și livrarea.","/marketplace"],
 ["Battery sizing","Dimensionarea bateriei","Is 100 Ah enough for my home?","Ajung 100 Ah pentru casă?","Ah alone cannot answer this. Multiply by nominal voltage, apply usable depth and conversion losses, then compare with measured load energy and BMS current limits.","Ah singur nu răspunde. Înmulțește cu tensiunea nominală, aplică utilizarea și pierderile, apoi compară cu energia măsurată și limitele BMS.","/learn/how-to-size-backup-battery"],
 ["Inverters","Invertoare","Why does my inverter trip at startup?","De ce declanșează invertorul la pornire?","The starting load may exceed the timed surge rating, or battery voltage may sag. Check the battery BMS, cables, terminals and inverter curve as one system.","Pornirea poate depăși vârful temporizat sau tensiunea bateriei poate scădea. Verifică BMS, cablurile, bornele și curba invertorului ca sistem.","/learn/inverter-surge-power"],
 ["Solar","Solar","Will roof panels work during an outage?","Funcționează panourile când cade rețeaua?","Not necessarily. A grid-tied inverter often stops without a supported backup/islanding arrangement. Verify the actual inverter, storage and transfer design.","Nu neapărat. Invertorul conectat la rețea se oprește adesea fără rezervă/insularizare compatibilă. Verifică invertorul, stocarea și transferul real.","/solutions/solar-battery"],
 ["Backup systems","Sisteme de rezervă","Does a bigger battery mean more power?","O baterie mai mare înseamnă putere mai mare?","More stored energy can extend runtime. Continuous and starting power are separately limited by the battery, BMS, inverter and wiring.","Energia mai mare poate extinde autonomia. Puterea continuă și de pornire este limitată separat de baterie, BMS, invertor și cabluri.","/backup-calculator"],
 ["Affiliate / suppliers","Afiliere / furnizori","Are you an approved Renogy affiliate?","Sunteți afiliat Renogy aprobat?","Approval is not confirmed. Renogy EU is the first intended affiliate supplier. Current links are ordinary external supplier links.","Aprobarea nu este confirmată. Renogy EU este primul furnizor vizat. Linkurile actuale sunt linkuri externe normale.","/affiliate-disclosure"],
 ["Safety","Siguranță","Can I use a generator inside a garage?","Pot folosi generatorul în garaj?","No. Combustion generators must operate outdoors away from openings, following manufacturer and local safety requirements. Open doors do not make indoor operation safe.","Nu. Generatorul cu ardere funcționează în exterior, departe de deschideri, conform producătorului și cerințelor locale. Ușile deschise nu fac sigură utilizarea în interior.","/learn/generator-vs-battery-backup"],
];
export const metadata=buildMetadata({title:"FAQ — cumpărare și dimensionare / buying and sizing",description:"Answers about battery sizing, inverters, solar backup, suppliers, affiliation and safety.",path:"/faq"});
export default async function Page(){const ro=await getRequestLocale()==="ro";return <PlatformShell><main className="commerce-page"><Intro title={ro?"Întrebări frecvente":"Frequently asked questions"} description={ro?"Răspunsuri pentru alegerea echipamentelor și înțelegerea rolului platformei.":"Answers for choosing equipment and understanding the platform's role."}/>{questions.map(([group,groupRo,q,qRo,a,aRo,path])=><section className="content-panel" key={group}><h2>{ro?groupRo:group}</h2><details open><summary>{ro?qRo:q}</summary><p>{ro?aRo:a}</p><Link href={path}>{ro?"Află mai mult":"Learn more"} →</Link></details></section>)}</main></PlatformShell>;}
